### ISSUE TITLE
ask for help: ImportError: Module "sentence_transformers.models" does not define a "BERT" attribute/class

### ISSUE THREAD

**Issue by linjianghao** [UKPLab/sentence-transformers#1080]
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('bert-large-nli-mean-tokens')

i got this error:
ImportError: Module "sentence_transformers.models" does not define a "BERT" attribute/class

**Comment by linjianghao** [comment]
the full error info as follow:

C:\Users\Thinkpad\AppData\Local\Programs\Python\Python37\python.exe D:/pythonwork/BLS_CODE_PYTHON/sentence_embeddings.py
2021-07-25 16:49:25.171098: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2021-07-25 16:49:25.171233: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
I0725 16:49:27.655274 28460 SentenceTransformer.py:60] Load pretrained SentenceTransformer: bert-large-nli-mean-tokens
Traceback (most recent call last):
  File "C:\Users\Thinkpad\AppData\Local\Programs\Python\Python37\lib\site-packages\sentence_transformers\util.py", line 299, in import_from_string
    return getattr(module, class_name)
AttributeError: module 'sentence_transformers.models' has no attribute 'BERT'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/pythonwork/BLS_CODE_PYTHON/sentence_embeddings.py", line 98, in <module>
    app.run(main)
  File "C:\Users\Thinkpad\AppData\Local\Programs\Python\Python37\lib\site-packages\absl\app.py", line 312, in run
    _run_main(main, args)
  File "C:\Users\Thinkpad\AppData\Local\Programs\Python\Python37\lib\site-packages\absl\app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "D:/pythonwork/BLS_CODE_PYTHON/sentence_embeddings.py", line 72, in main
    model = SentenceTransformer('bert-large-nli-mean-tokens')
  File "C:\Users\Thinkpad\AppData\Local\Programs\Python\Python37\lib\site-packages\sentence_transformers\SentenceTransformer.py", line 90, in __init__
    modules = self._load_sbert_model(model_path)
  File "C:\Users\Thinkpad\AppData\Local\Programs\Python\Python37\lib\site-packages\sentence_transformers\SentenceTransformer.py", line 821, in _load_sbert_model
    module_class = import_from_string(module_config['type'])
  File "C:\Users\Thinkpad\AppData\Local\Programs\Python\Python37\lib\site-packages\sentence_transformers\util.py", line 302, in import_from_string
    raise ImportError(msg)
ImportError: Module "sentence_transformers.models" does not define a "BERT" attribute/class

Process finished with exit code 1

**Comment by nreimers** [comment]
Try to remove the .cache/torch/sentence-transformer folder and try to run again.

I strongly recommend to use one of the newer models. The bert-large-nli-mean-tokens works horribly bad. Recommended models can be found in our docs.

**Comment by linjianghao** [comment]
> Try to remove the .cache/torch/sentence-transformer folder and try to run again.
> 
> I strongly recommend to use one of the newer models. The bert-large-nli-mean-tokens works horribly bad. Recommended models can be found in our docs.

thank you very much

**Comment by winthroptsmith** [comment]
I get this error while a colleague of mine does not.  We are running the same model (nlpaueb_legal-bert-base-uncased), the same version of sentence-transformers, and the same versions of most other python modules.  Does anyone have any suggestions?  Thank you

**Comment by nreimers** [comment]
The models.BERT class was at some point replaced by models.Transformer and then later models.BERT was removed.

I assume that you have still some old cache files. Try to clean your cache folder: ~/.cache/torch/sentence-transformers

**Comment by winthroptsmith** [comment]
Thank you very much for the quick response.  I don't seem to have that cache folder.  Do you have any other suggestions?

**Comment by nreimers** [comment]
You can create your sentence transformers model from scratch like this:
https://www.sbert.net/docs/training/overview.html#creating-networks-from-scratch

**Comment by winthroptsmith** [comment]
Thanks.  I finally made it work just by copying down the model again from our server.  Thanks again.
