### ISSUE TITLE
OSError: libcudart.so.9.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Jacob-fu-smith** [UKPLab/sentence-transformers#1108]
**import Error:**
```
>>> import sentence_transformers
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jin/anaconda3/envs/zr/lib/python3.6/site-packages/sentence_transformers/__init__.py", line 3, in <module>
    from .datasets import SentencesDataset, ParallelSentencesDataset
  File "/home/jin/anaconda3/envs/zr/lib/python3.6/site-packages/sentence_transformers/datasets/__init__.py", line 1, in <module>
    from .ParallelSentencesDataset import ParallelSentencesDataset
  File "/home/jin/anaconda3/envs/zr/lib/python3.6/site-packages/sentence_transformers/datasets/ParallelSentencesDataset.py", line 4, in <module>
    from .. import SentenceTransformer
  File "/home/jin/anaconda3/envs/zr/lib/python3.6/site-packages/sentence_transformers/SentenceTransformer.py", line 24, in <module>
    from .models import Transformer, Pooling
  File "/home/jin/anaconda3/envs/zr/lib/python3.6/site-packages/sentence_transformers/models/__init__.py", line 1, in <module>
    from .Transformer import Transformer
  File "/home/jin/anaconda3/envs/zr/lib/python3.6/site-packages/sentence_transformers/models/Transformer.py", line 2, in <module>
    from transformers import AutoModel, AutoTokenizer, AutoConfig
  File "<frozen importlib._bootstrap>", line 1006, in _handle_fromlist
  File "/home/jin/anaconda3/envs/zr/lib/python3.6/site-packages/transformers/file_utils.py", line 1985, in __getattr__
    value = getattr(module, name)
  File "/home/jin/anaconda3/envs/zr/lib/python3.6/site-packages/transformers/file_utils.py", line 1984, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/home/jin/anaconda3/envs/zr/lib/python3.6/site-packages/transformers/file_utils.py", line 1993, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/home/jin/anaconda3/envs/zr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/jin/anaconda3/envs/zr/lib/python3.6/site-packages/transformers/models/auto/modeling_auto.py", line 271, in <module>
    from ..tapas.modeling_tapas import (
  File "/home/jin/anaconda3/envs/zr/lib/python3.6/site-packages/transformers/models/tapas/modeling_tapas.py", line 51, in <module>
    from torch_scatter import scatter
  File "/home/jin/anaconda3/envs/zr/lib/python3.6/site-packages/torch_scatter/__init__.py", line 12, in <module>
    library, [osp.dirname(__file__)]).origin)
  File "/home/jin/anaconda3/envs/zr/lib/python3.6/site-packages/torch/_ops.py", line 105, in load_library
    ctypes.CDLL(path)
  File "/home/jin/anaconda3/envs/zr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcudart.so.9.2: cannot open shared object file: No such file or directory
```
i have tried serial version of `sentence-transformers`, and it seems like version-independent, 
the torch version is `1.6.0+cu101` and  i can import torch with gpu withou any Error.
i have tried the method like but i have no permisssion of sudo:
```
export LD_LIBRARY_PATH=/usr/local/cuda-9.2/lib64:$LD_LIBRARY_PATH
export PATH=/usr/local/cuda-9.2/bin:$PATH
```
as well as `cuda-10.1`

the information of  /usr/local looks like this:
```
(zr) [jin@gpu03 local]$ pwd
/usr/local
(zr) [jin@gpu03 local]$ ll
总用量 12
drwxr-xr-x.  2 root root    6 7月  10 2020 bin
lrwxrwxrwx   1 root root   21 6月   1 2020 cuda -> /usr/local/cuda-10.1/
drwxr-xr-x  18 root root  319 6月   1 2020 cuda-10.1
drwxr-xr-x  18 root root  249 7月  20 2018 cuda-9.0
drwxr-xr-x.  2 root root    6 11月  5 2016 etc
drwxr-xr-x.  2 root root    6 11月  5 2016 games
drwxr-xr-x   8 root root   84 3月  16 14:21 gcc
drwxr-xr-x.  4 root root   33 8月  11 2020 include
drwxr-xr-x.  4 root root 8192 8月  11 2020 lib
drwxr-xr-x.  2 root root    6 11月  5 2016 lib64
drwxr-xr-x.  2 root root    6 11月  5 2016 libexec
drwxr-xr-x.  2 root root    6 11月  5 2016 sbin
drwxr-xr-x.  5 root root   49 7月  14 2018 share
drwxr-xr-x.  3 root root   48 3月  16 11:29 src
```
what should i do?

**Comment by nreimers** [comment]
It appears that torch is not correctly installed with CUDA.

Have a look here:
https://pytorch.org/get-started

How to use conda to install pytorch with CUDA.

You can test it with:
```
import torch
print(torch.cuda.is_available())
a = torch.tensor([1], device='cuda')
```

**Comment by Jacob-fu-smith** [comment]
> It appears that torch is not correctly installed with CUDA.
> 
> Have a look here:
> https://pytorch.org/get-started
> 
> How to use conda to install pytorch with CUDA.
> 
> You can test it with:
> 
> ```
> import torch
> print(torch.cuda.is_available())
> a = torch.tensor([1], device='cuda')
> ```

the torch with cuda works fine.Test with following command:
```
>>> import torch
>>> torch.cuda.device_count()
1
>>> torch.cuda.get_device_name(0)
'Tesla P100-PCIE-12GB'
>>> torch.cuda.is_available()
True
>>> torch.randn([3,1]).to('cuda')
tensor([[ 1.4978],
        [ 1.2027],
        [-0.5271]], device='cuda:0')
```
other python scripts without sentence-transformers works fine as well. i don't know what to do.

**Comment by nreimers** [comment]
Does this code work?
```python
from transformers import AutoTokenizer, AutoModel
import torch


#Mean Pooling - Take attention mask into account for correct averaging
def mean_pooling(model_output, attention_mask):
    token_embeddings = model_output[0] #First element of model_output contains all token embeddings
    input_mask_expanded = attention_mask.unsqueeze(-1).expand(token_embeddings.size()).float()
    return torch.sum(token_embeddings * input_mask_expanded, 1) / torch.clamp(input_mask_expanded.sum(1), min=1e-9)


# Sentences we want sentence embeddings for
sentences = ['This is an example sentence', 'Each sentence is converted']

# Load model from HuggingFace Hub
tokenizer = AutoTokenizer.from_pretrained('sentence-transformers/paraphrase-distilroberta-base-v2')
model = AutoModel.from_pretrained('sentence-transformers/paraphrase-distilroberta-base-v2')

model.cuda()

# Tokenize sentences
encoded_input = tokenizer(sentences, padding=True, truncation=True, return_tensors='pt').cuda()

# Compute token embeddings
with torch.no_grad():
    model_output = model(**encoded_input)

# Perform pooling. In this case, max pooling.
sentence_embeddings = mean_pooling(model_output, encoded_input['attention_mask'])

print("Sentence embeddings:")
print(sentence_embeddings)
```

**Comment by Jacob-fu-smith** [comment]
> Does this code work?
> 
> ```python
> from transformers import AutoTokenizer, AutoModel
> import torch
> 
> 
> #Mean Pooling - Take attention mask into account for correct averaging
> def mean_pooling(model_output, attention_mask):
>     token_embeddings = model_output[0] #First element of model_output contains all token embeddings
>     input_mask_expanded = attention_mask.unsqueeze(-1).expand(token_embeddings.size()).float()
>     return torch.sum(token_embeddings * input_mask_expanded, 1) / torch.clamp(input_mask_expanded.sum(1), min=1e-9)
> 
> 
> # Sentences we want sentence embeddings for
> sentences = ['This is an example sentence', 'Each sentence is converted']
> 
> # Load model from HuggingFace Hub
> tokenizer = AutoTokenizer.from_pretrained('sentence-transformers/paraphrase-distilroberta-base-v2')
> model = AutoModel.from_pretrained('sentence-transformers/paraphrase-distilroberta-base-v2')
> 
> model.cuda()
> 
> # Tokenize sentences
> encoded_input = tokenizer(sentences, padding=True, truncation=True, return_tensors='pt').cuda()
> 
> # Compute token embeddings
> with torch.no_grad():
>     model_output = model(**encoded_input)
> 
> # Perform pooling. In this case, max pooling.
> sentence_embeddings = mean_pooling(model_output, encoded_input['attention_mask'])
> 
> print("Sentence embeddings:")
> print(sentence_embeddings)
> ```

well, it doesn't work, the same error :
```
Traceback (most recent call last):
  File "Test.py", line 1, in <module>
    from transformers import AutoTokenizer, AutoModel
  File "<frozen importlib._bootstrap>", line 1006, in _handle_fromlist
  File "/home/jin/anaconda3/envs/zr/lib/python3.6/site-packages/transformers/file_utils.py", line 1985, in __getattr__
    value = getattr(module, name)
  File "/home/jin/anaconda3/envs/zr/lib/python3.6/site-packages/transformers/file_utils.py", line 1984, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/home/jin/anaconda3/envs/zr/lib/python3.6/site-packages/transformers/file_utils.py", line 1993, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/home/jin/anaconda3/envs/zr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/jin/anaconda3/envs/zr/lib/python3.6/site-packages/transformers/models/auto/modeling_auto.py", line 271, in <module>
    from ..tapas.modeling_tapas import (
  File "/home/jin/anaconda3/envs/zr/lib/python3.6/site-packages/transformers/models/tapas/modeling_tapas.py", line 51, in <module>
    from torch_scatter import scatter
  File "/home/jin/anaconda3/envs/zr/lib/python3.6/site-packages/torch_scatter/__init__.py", line 12, in <module>
    library, [osp.dirname(__file__)]).origin)
  File "/home/jin/anaconda3/envs/zr/lib/python3.6/site-packages/torch/_ops.py", line 105, in load_library
    ctypes.CDLL(path)
  File "/home/jin/anaconda3/envs/zr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcudart.so.9.2: cannot open shared object file: No such file or directory
```

**Comment by nreimers** [comment]
As mentioned, it appears that Cuda / pytorch is not correct installed. I recommend to create a new environment and to install there first pytorch with the correct Cuda version using the conda commands from the pytorch website

**Comment by Jacob-fu-smith** [comment]
Woo!
The previous torch is installed with pip, and that's what does really matter(though i don't have a deep understanding).
I have a close look at [the difference between `conda` and `pip`](https://www.anaconda.com/blog/understanding-conda-and-pip), installing torch-gpu with `conda` really works.
Thanks!

**Comment by Jacob-fu-smith** [comment]
Thanks for commenting my problem with such a patience!
