### ISSUE TITLE
pip install -U sentence-transformers with an  error

### ISSUE THREAD

**Issue by HenryBao91** [UKPLab/sentence-transformers#1118]
`pip install -U sentence-transformers`
I install it using pip ，it occurs an error.
`
[root@master]# pip install -U sentence-transformers
Collecting sentence-transformers
  Downloading http://mirrors.aliyun.com/pypi/packages/3b/fd/8a81047bbd9fa134a3f27e12937d2a487bd49d353a038916a5d7ed4e5543/sentence-transformers-2.0.0.tar.gz (85kB)
    100% |████████████████████████████████| 92kB 6.7MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-Pt2IR2/sentence-transformers/setup.py", line 3, in <module>
        with open("README.md", mode="r", encoding="utf-8") as readme_file:
    TypeError: 'encoding' is an invalid keyword argument for this function
    ----------------------------------------
`

**Comment by HenryBao91** [comment]
I fix this error.Change ‘seup.py’ ：
`
with open('README.txt','r',encoding='utf-8') as f:
    lines = f.readlines()
    ...
`
My code：
`
import io
with io.open('README.txt','r',encoding='utf-8') as f:
    lines = f.readlines()
`
and then, 
'python setup.py install`
successful

**Comment by nreimers** [comment]
Are you running Python 2? Sentence Transformers will not work with Python 2, Python 3.6 or newer is required
