### ISSUE TITLE
Cannot download model 

### ISSUE THREAD

**Issue by MaggieX** [UKPLab/sentence-transformers#1161]
Was able to download with the same code earlier, but I have been receiving connection refused error all day today. Is it due to any change to the remote path of the model?

```
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fe570b53198>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/sentence-transformers/distilbert-base-nli-mean-tokens (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe570b53198>: Failed to establish a new connection: [Errno 111] Connection refused',)))
```

**Comment by averkij** [comment]
It says "Cannot connect to proxy".
Can you download other models? Which code do you use for downloading?
