### ISSUE TITLE
Error when importing: got_ver is None 

### ISSUE THREAD

**Issue by sinaahmadi** [UKPLab/sentence-transformers#1186]
Hi,

When importing `SentenceTransformer`, the following error is raised:

```
>>> from sentence_transformers import SentenceTransformer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/sentence_transformers/__init__.py", line 3, in <module>
    from .datasets import SentencesDataset, ParallelSentencesDataset
  File "/usr/local/lib/python3.9/site-packages/sentence_transformers/datasets/__init__.py", line 3, in <module>
    from .ParallelSentencesDataset import ParallelSentencesDataset
  File "/usr/local/lib/python3.9/site-packages/sentence_transformers/datasets/ParallelSentencesDataset.py", line 4, in <module>
    from .. import SentenceTransformer
  File "/usr/local/lib/python3.9/site-packages/sentence_transformers/SentenceTransformer.py", line 11, in <module>
    import transformers
  File "/usr/local/lib/python3.9/site-packages/transformers/__init__.py", line 43, in <module>
    from . import dependency_versions_check
  File "/usr/local/lib/python3.9/site-packages/transformers/dependency_versions_check.py", line 41, in <module>
    require_version_core(deps[pkg])
  File "/usr/local/lib/python3.9/site-packages/transformers/utils/versions.py", line 120, in require_version_core
    return require_version(requirement, hint)
  File "/usr/local/lib/python3.9/site-packages/transformers/utils/versions.py", line 114, in require_version
    _compare_versions(op, got_ver, want_ver, requirement, pkg, hint)
  File "/usr/local/lib/python3.9/site-packages/transformers/utils/versions.py", line 45, in _compare_versions
    raise ValueError("got_ver is None")
ValueError: got_ver is None
```

I am using Python 3.9.4, `transformers` version 4.6.0, `allennlp` version 2.7.0, `huggingface-hub` version 0.0.8 and `tokenizers` version 0.10.3.

Thanks for your help!

**Comment by nreimers** [comment]
Could it be that you have some subfolders, that conflict with their name to some packages (like having a 'transformers' subfolder or a 'datasets' subfolder where you have your script).

**Comment by sinaahmadi** [comment]
Thanks for your reply, @nreimers.
No, I just installed the package and have no subfolder or dataset with the same name.

**Comment by nreimers** [comment]
Could it be an issue with tqdm?
https://www.reddit.com/r/learnpython/comments/oqs9o9/valueerror_when_importing_the_transformers_module/

**Comment by sinaahmadi** [comment]
It's unluckily not the case. 
I tried upgrading the required packages. When upgrading `huggingface-hub`, the following is raised:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
transformers 4.6.0 requires huggingface-hub==0.0.8, but you have huggingface-hub 0.0.17 which is incompatible.
```
And when I install that specific version of 0.0.8, the following is raised:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
datasets 1.12.1 requires huggingface-hub<0.1.0,>=0.0.14, but you have huggingface-hub 0.0.8 which is incompatible.
```

Any help would be much appreciated!

**Comment by nreimers** [comment]
Maybe create a clean virtual env and start from  there. I can recommend to use miniconda:
https://docs.conda.io/en/latest/miniconda.html

Then create there a clean environment with conda, install Pytorch (with GPU), then do `pip install sentence-transformers`

**Comment by AlphaNext** [comment]
Your environment may have multi version numpy package, please check numpy version and reinstall this package. Hope this could help you.

**Comment by tomaarsen** [comment]
The above suggestions should help in avoiding this issue! I'll close this for now.
