### ISSUE TITLE
Error loading pretrained model

### ISSUE THREAD

**Issue by aclifton314** [UKPLab/sentence-transformers#1197]
Sentence-Transformers 2.1.0
Pytorch 1.9.1
Python 3.9.7
Using a conda venv.

The following code:
```python
from sentence_transformers import SentenceTransformer, util
model = SentenceTransformer('paraphrase-MiniLM-L6-v2')
```

produces the below error:
```python
Traceback (most recent call last):
  File "/proj/1117577/venvs/jca-ai/lib/python3.9/site-packages/urllib3/connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "/proj/1117577/venvs/jca-ai/lib/python3.9/site-packages/urllib3/connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "/proj/1117577/venvs/jca-ai/lib/python3.9/site-packages/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
  File "/proj/1117577/venvs/jca-ai/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/proj/1117577/venvs/jca-ai/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/proj/1117577/venvs/jca-ai/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/proj/1117577/venvs/jca-ai/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/proj/1117577/venvs/jca-ai/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/proj/1117577/venvs/jca-ai/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/proj/1117577/venvs/jca-ai/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/proj/1117577/venvs/jca-ai/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/sentence-transformers/paraphrase-MiniLM-L6-v2 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/proj/1117577/sbert_eval/ootb_eval.py", line 70, in <module>
    model = SentenceTransformer('paraphrase-MiniLM-L6-v2')
  File "/proj/1117577/venvs/jca-ai/lib/python3.9/site-packages/sentence_transformers/SentenceTransformer.py", line 80, in __init__
    snapshot_download(model_name_or_path,
  File "/proj/1117577/venvs/jca-ai/lib/python3.9/site-packages/sentence_transformers/util.py", line 426, in snapshot_download
    model_info = _api.model_info(repo_id=repo_id, revision=revision)
  File "/proj/1117577/venvs/jca-ai/lib/python3.9/site-packages/huggingface_hub/hf_api.py", line 516, in model_info
    r = requests.get(path, headers=headers, timeout=timeout)
  File "/proj/1117577/venvs/jca-ai/lib/python3.9/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/proj/1117577/venvs/jca-ai/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/proj/1117577/venvs/jca-ai/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/proj/1117577/venvs/jca-ai/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/proj/1117577/venvs/jca-ai/lib/python3.9/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/sentence-transformers/paraphrase-MiniLM-L6-v2 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)')))
```

despite having the model in `~/.cache/torch/sentence_transformers`. Any idea about what might be going on? I am behind a proxy but I have successfully configured `conda`, `pip`, and `wget` and have used them successfully.

**Comment by nreimers** [comment]
It is likely due to the proxy. In v2.1 there is a check for new model files.

Solution: save the model files to some other folder and load the model with
SentenceTransformer("my/folder/path")
