### ISSUE TITLE
ModuleNotFoundError: No module named 'sentence_transformers' working with FastAPI

### ISSUE THREAD

**Issue by Swty13** [UKPLab/sentence-transformers#1240]
I have a very simple application to expose the Sentence Transformer.
fastapi==0.52.0
sentence-transformers==1.2.0 ( I tried with v2.0)
python=3.6.5

`
from fastapi import FastAPI
from sentence_transformers import SentenceTransformer
app = FastAPI()
    
model = SentenceTransformer("sentence-transformers/paraphrase-MiniLM-L6-v2")
        
@app.post('/')
def encodeSentences(sentences: List[str]):
    embeddings = model.encode(sentences).tolist()
    return embeddings
`
for which I start getting the following error:

Process SpawnProcess-6:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/uvicorn/subprocess.py", line 61, in subprocess_started
    target(sockets=sockets)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/uvicorn/server.py", line 49, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/uvicorn/server.py", line 56, in serve
    config.load()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/uvicorn/config.py", line 308, in load
    self.loaded_app = import_from_string(self.app)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/uvicorn/importer.py", line 23, in import_from_string
    raise exc from None
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/uvicorn/importer.py", line 20, in import_from_string
    module = importlib.import_module(module_str)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "./test.py", line 4, in <module>
    from sentence_transformers import SentenceTransformer
ModuleNotFoundError: No module named 'sentence_transformers'

Thanks in advance .. !!!

**Comment by nreimers** [comment]
Appears that it is not installed in the env you use to start the FastApi service

**Comment by qaixerabbas** [comment]
I would suggest to create a venv and install libraires in that env. This would ensure that there is no installation issue.
