### ISSUE TITLE
Problem with CLIP model (clip-ViT-B-32)

### ISSUE THREAD

**Issue by lualeperez** [UKPLab/sentence-transformers#1241]
Hello all,

I am experiencing an error when loading the clip model clip-ViT-B-32. I am on macOS Big Sur Version 11.5.2. I am also using python 3.9 and the following versions of related packages

```
torch==1.8.1
torchmetrics==0.5.1
torchvision==0.9.1
numpy==1.20.3
ftfy==6.0.3
transformers==4.9.2
ipywidgets==7.6.3
nbformat==5.1.3
sentence-transformers==2.0.0
Pillow==8.3.2
```

When I do 

```
>>> from sentence_transformers import SentenceTransformer
>>> model = SentenceTransformer("clip-ViT-B-32")
```

I get the following error
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mypath/venv/lib/python3.9/site-packages/sentence_transformers/SentenceTransformer.py", line 90, in __init__
    modules = self._load_sbert_model(model_path)
  File "/mypath/venv/lib/python3.9/site-packages/sentence_transformers/SentenceTransformer.py", line 822, in _load_sbert_model
    module = module_class.load(os.path.join(model_path, module_config['path']))
  File "/mypath/venv/lib/python3.9/site-packages/sentence_transformers/models/CLIPModel.py", line 90, in load
    model_path = os.path.join(input_path, config['model_name'])
KeyError: 'model_name'
```
The system manages to download the model and store it in the cache (`$HOME/.cache/torch/sentence_transformers/sentence-transformers_clip-ViT-B-32/`), but is seems that it lacks a `config.json` file there.

Any help will be appreciated.

Thanks,

  Alejandro

**Comment by nreimers** [comment]
You need to upgrade to v2.1.0 or downgrade to 1.2.1.

The CLIP model does no longer work with version 2.0.0 due to a breaking change introduced in 2.1.0

**Comment by lualeperez** [comment]
thank you very much. I will update to v2.1.0.

**Comment by hassanazhar** [comment]
Hello, I have updated to v2.1.0 but cannot load the CLIP model from huggingface. The code below works for huggingface text models, is there something similar for ViT?

`word_embedding_model = models.BERT('path/to/your/bert/model')

# Apply mean pooling to get one fixed sized sentence vector
pooling_model = models.Pooling(word_embedding_model.get_word_embedding_dimension(),
                               pooling_mode_mean_tokens=True,
                               pooling_mode_cls_token=False,
                               pooling_mode_max_tokens=False)

model = SentenceTransformer(modules=[word_embedding_model, pooling_model])`

**Comment by nreimers** [comment]
@hassanazhar You might need to delete the entry (the folder) for the clip model in the cache folder ~/.cache/torch/sentence_transformers.

Otherwise you can create it like this:
```
from sentence_transformers import models, SentenceTransformer
clip_model = models.CLIPModel()
model = SentenceTransformer(modules=[clip_model])
```
