### ISSUE TITLE
sentence transformers to TorchScript - try blocks aren't supported

### ISSUE THREAD

**Issue by omrivm** [UKPLab/sentence-transformers#1261]
When i try to convert a sentence transformers model to TorchScript i get: try blocks aren't supported

```
from sentence_transformers import SentenceTransformer, util
model = SentenceTransformer( "sentence-transformers/msmarco-MiniLM-L-6-v3", device='cuda')
pts = torch.jit.script(model)
```
stack trace:
```
Traceback (most recent call last):
  File "/pycharm-2021.2.1/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "/anaconda3/envs/cm_nlp/lib/python3.7/site-packages/torch/jit/_script.py", line 1097, in script
    obj, torch.jit._recursive.infer_methods_to_compile
  File "/anaconda3/envs/cm_nlp/lib/python3.7/site-packages/torch/jit/_recursive.py", line 412, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
  File "/anaconda3/envs/cm_nlp/lib/python3.7/site-packages/torch/jit/_recursive.py", line 425, in create_script_module_impl
    property_stubs = get_property_stubs(nn_module)
  File "/anaconda3/envs/cm_nlp/lib/python3.7/site-packages/torch/jit/_recursive.py", line 735, in get_property_stubs
    properties_asts = get_class_properties(module_ty, self_name="RecursiveScriptModule")
  File "/anaconda3/envs/cm_nlp/lib/python3.7/site-packages/torch/jit/frontend.py", line 161, in get_class_properties
    getter = get_jit_def(prop[1].fget, f"__{prop[0]}_getter", self_name=self_name)
  File "/anaconda3/envs/cm_nlp/lib/python3.7/site-packages/torch/jit/frontend.py", line 308, in get_jit_def
    return build_def(ctx, fn_def, type_line, def_name, self_name=self_name, pdt_arg_types=pdt_arg_types)
  File "/anaconda3/envs/cm_nlp/lib/python3.7/site-packages/torch/jit/frontend.py", line 359, in build_def
    build_stmts(ctx, body))
  File "/anaconda3/envs/cm_nlp/lib/python3.7/site-packages/torch/jit/frontend.py", line 137, in build_stmts
    stmts = [build_stmt(ctx, s) for s in stmts]
  File "/anaconda3/envs/cm_nlp/lib/python3.7/site-packages/torch/jit/frontend.py", line 137, in <listcomp>
    stmts = [build_stmt(ctx, s) for s in stmts]
  File "/anaconda3/envs/cm_nlp/lib/python3.7/site-packages/torch/jit/frontend.py", line 330, in __call__
    raise UnsupportedNodeError(ctx, node)
torch.jit.frontend.UnsupportedNodeError: try blocks aren't supported:
  File "/anaconda3/envs/cm_nlp/lib/python3.7/site-packages/sentence_transformers/SentenceTransformer.py", line 853
        Get torch.device from module, assuming that the whole module has one device.
        """
        try:
        ~~~ <--- HERE
            return next(self.parameters()).device
        except StopIteration:
```

Can anyone guide me where is my mistake?

**Comment by nreimers** [comment]
Maybe these two PRs are helpful:
https://github.com/UKPLab/sentence-transformers/pull/386
https://github.com/UKPLab/sentence-transformers/pull/668

**Comment by pavanchhatpar** [comment]
Is there a workaround for this?

**Comment by hh23485** [comment]
The same problem to me, any ideas about this?
