### ISSUE TITLE
Error in Installation

### ISSUE THREAD

**Issue by tkhan3** [UKPLab/sentence-transformers#128]
I am trying to install sentence transformers library with Python 3.7 in a virtual environment. I have installed pytorch 1.4 in same conda environment.

I am using REDHAT.

But I am facing below error while installation. I have tried with direct pip installation and by checking out code and used pip -e option. Kindly help.

  ```
Using cached sentencepiece-0.1.83.tar.gz (497 kB)
    ERROR: Command errored out with exit status 1:
     command: /power8nfs/home/ai_u/.conda/envs/tanveer/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-6kz16kgn/sentencepiece/setup.py'"'"'; __file__='"'"'/tmp/pip-install-6kz16kgn/sentencepiece/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-6kz16kgn/sentencepiece/pip-egg-info
         cwd: /tmp/pip-install-6kz16kgn/sentencepiece/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-6kz16kgn/sentencepiece/setup.py", line 29, in <module>
        with codecs.open(os.path.join('..', 'VERSION'), 'r', 'utf-8') as f:
      File "/power8nfs/home/ai_u/.conda/envs/tanveer/lib/python3.7/codecs.py", line 904, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '../VERSION'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```

**Comment by nreimers** [comment]
It is an issue with sentence piece. See
https://github.com/google/sentencepiece/issues/386

**Comment by tkhan3** [comment]
> 
> 
> It is an issue with sentence piece. See
> [google/sentencepiece#386](https://github.com/google/sentencepiece/issues/386)

I am sorry for not clarifying it. I am installing it on a Redhat.

VERSION="7.7 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.7"
PRETTY_NAME="OpenShift Enterprise"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.7:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

**Comment by nreimers** [comment]
The issue is with the installation of sentence piece. Sadly not sure what the issue is there.

You could try to install sentence transformers without dependencies:
```
pip install --no-deps sentence-transformers 
```

And than install individually the different dependencies:
```
https://github.com/UKPLab/sentence-transformers/blob/master/requirements.txt
```

transformers requires sentence piece for the XLM-R model. Maybe you need to install it also without dependencies.

Without sentence piece, all models except the XLM-RoBERTa model will work.  So you can still use BERT or RoBERTa models for your task.

Best
Nils Reimers

**Comment by tkhan3** [comment]
@nreimers thanks. Tried same but while installing transformer dependency it's again invoking sentence piece.

```
(tanveer) [ai_u@powcbds tanveer]$ pip install --no-deps sentence-transformers
Requirement already satisfied: sentence-transformers in /power8nfs/home/ai_u/.conda/envs/tanveer/lib/python3.7/site-packages/sentence_transformers-0.2.5-py3.7.egg (0.2.5)
(tanveer) [ai_u@powcbds tanveer]$ pip install transformers==2.3.0
Collecting transformers==2.3.0
  Using cached transformers-2.3.0-py3-none-any.whl (447 kB)
Collecting regex!=2019.12.17
  Using cached regex-2020.1.8.tar.gz (681 kB)
Collecting sentencepiece
  Using cached sentencepiece-0.1.83.tar.gz (497 kB)
    ERROR: Command errored out with exit status 1:
     command: /power8nfs/home/ai_u/.conda/envs/tanveer/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-3u3uxl6b/sentencepiece/setup.py'"'"'; __file__='"'"'/tmp/pip-install-3u3uxl6b/sentencepiece/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-3u3uxl6b/sentencepiece/pip-egg-info
         cwd: /tmp/pip-install-3u3uxl6b/sentencepiece/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-3u3uxl6b/sentencepiece/setup.py", line 29, in <module>
        with codecs.open(os.path.join('..', 'VERSION'), 'r', 'utf-8') as f:
      File "/power8nfs/home/ai_u/.conda/envs/tanveer/lib/python3.7/codecs.py", line 904, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '../VERSION'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```

**Comment by tkhan3** [comment]
@nreimers Thanks for your guidance. As you pointed out issue is with sentencepiece from google. What I observed there is some issue with their PIP package. I installed sentencepiece via conda distribution and it worked. 
Below are the steps that 

```
pip install --no-deps sentence-transformers 
conda install nltk
conda install scipy
conda install scikit-learn
conda install -c powerai sentencepiece
conda install numpy
conda install tqdm
pip install transformers==2.3.0

```

Thanks for your help !!

**Comment by nreimers** [comment]
Great that it worked and thanks for posting the solution.
