### ISSUE TITLE
"IndexError: index_select(): Index is supposed to be a vector" when convert model to onnx format

### ISSUE THREAD

**Issue by GodsDusk** [UKPLab/sentence-transformers#1296]
python3.8
torch 1.10
sentence-transformers 2.1.0

model defined as tutorial
```python
word_embedding_model = models.Transformer(PRETRAINED_MODEL, max_seq_length=256, cache_dir='../cache')
pooling_model = models.Pooling(word_embedding_model.get_word_embedding_dimension(),
                               pooling_mode_mean_tokens=True,
                               pooling_mode_cls_token=False,
                               pooling_mode_max_tokens=False)

model = SentenceTransformer(modules=[word_embedding_model, pooling_model])
```

here is my convert code:
```python
model = SentenceTransformer('my_model')
batch_size = 32
max_seq_length = 256
device = 'cpu'
input_ids = torch.zeros(batch_size, max_seq_length, dtype=torch.long).to(device)
input_type_ids = torch.zeros(batch_size, max_seq_length, dtype=torch.long).to(device)
input_mask = torch.zeros(batch_size, max_seq_length, dtype=torch.long).to(device)
input_features = {'input_ids': input_ids, 'token_type_ids': input_type_ids, 'attention_mask': input_mask}
torch.onnx.export(model, (input_features, {}), 'model.onnx', verbose=True)
```

and error:
```
[W shape_type_inference.cpp:434] Warning: Constant folding in symbolic shape inference fails: index_select(): Index is supposed to be a vector
Exception raised from index_select_out_cpu_ at ../aten/src/ATen/native/TensorAdvancedIndexing.cpp:887 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7f976e29ad62 in /home/project/anaconda3/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: at::native::index_select_out_cpu_(at::Tensor const&, long, at::Tensor const&, at::Tensor&) + 0x3a9 (0x7f97b556c469 in /home/project/anaconda3/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #2: at::native::index_select_cpu_(at::Tensor const&, long, at::Tensor const&) + 0xe6 (0x7f97b556e426 in /home/project/anaconda3/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #3: <unknown function> + 0x1d261f2 (0x7f97b5c661f2 in /home/project/anaconda3/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #4: at::_ops::index_select::redispatch(c10::DispatchKeySet, at::Tensor const&, long, at::Tensor const&) + 0xb9 (0x7f97b5801379 in /home/project/anaconda3/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #5: <unknown function> + 0x323eda3 (0x7f97b717eda3 in /home/project/anaconda3/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #6: <unknown function> + 0x323f3d5 (0x7f97b717f3d5 in /home/project/anaconda3/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #7: at::_ops::index_select::call(at::Tensor const&, long, at::Tensor const&) + 0x166 (0x7f97b5880fc6 in /home/project/anaconda3/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #8: torch::jit::onnx_constant_fold::runTorchBackendForOnnx(torch::jit::Node const*, std::vector<at::Tensor, std::allocator<at::Tensor> >&, int) + 0x1b5f (0x7f97cb532e0f in /home/project/anaconda3/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #9: <unknown function> + 0xbbd322 (0x7f97cb57a322 in /home/project/anaconda3/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #10: torch::jit::ONNXShapeTypeInference(torch::jit::Node*, std::map<std::string, c10::IValue, std::less<std::string>, std::allocator<std::pair<std::string const, c10::IValue> > > const&, int) + 0xa8e (0x7f97cb57fa7e in /home/project/anaconda3/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #11: <unknown function> + 0xbc4584 (0x7f97cb581584 in /home/project/anaconda3/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #12: <unknown function> + 0xb34d8c (0x7f97cb4f1d8c in /home/project/anaconda3/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #13: <unknown function> + 0x2a4f3e (0x7f97cac61f3e in /home/project/anaconda3/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #14: PyCFunction_Call + 0x56 (0x5586d299ff76 in /home/project/anaconda3/bin/python)
frame #15: _PyObject_MakeTpCall + 0x22f (0x5586d295d85f in /home/project/anaconda3/bin/python)
frame #16: <unknown function> + 0xffa68 (0x5586d291fa68 in /home/project/anaconda3/bin/python)
frame #17: _PyEval_EvalCodeWithName + 0x2d2 (0x5586d29aaa92 in /home/project/anaconda3/bin/python)
frame #18: _PyFunction_Vectorcall + 0x1e3 (0x5586d29ab943 in /home/project/anaconda3/bin/python)
frame #19: <unknown function> + 0x7df36 (0x5586d289df36 in /home/project/anaconda3/bin/python)
frame #20: <unknown function> + 0x1001de (0x5586d29201de in /home/project/anaconda3/bin/python)
frame #21: _PyEval_EvalCodeWithName + 0x2d2 (0x5586d29aaa92 in /home/project/anaconda3/bin/python)
frame #22: _PyFunction_Vectorcall + 0x1e3 (0x5586d29ab943 in /home/project/anaconda3/bin/python)
frame #23: <unknown function> + 0x7df36 (0x5586d289df36 in /home/project/anaconda3/bin/python)
frame #24: <unknown function> + 0x1001de (0x5586d29201de in /home/project/anaconda3/bin/python)
frame #25: _PyEval_EvalCodeWithName + 0x2d2 (0x5586d29aaa92 in /home/project/anaconda3/bin/python)
frame #26: _PyFunction_Vectorcall + 0x1e3 (0x5586d29ab943 in /home/project/anaconda3/bin/python)
frame #27: <unknown function> + 0x7df36 (0x5586d289df36 in /home/project/anaconda3/bin/python)
frame #28: <unknown function> + 0x1001de (0x5586d29201de in /home/project/anaconda3/bin/python)
frame #29: _PyEval_EvalCodeWithName + 0x2d2 (0x5586d29aaa92 in /home/project/anaconda3/bin/python)
frame #30: _PyFunction_Vectorcall + 0x1e3 (0x5586d29ab943 in /home/project/anaconda3/bin/python)
frame #31: <unknown function> + 0x7df36 (0x5586d289df36 in /home/project/anaconda3/bin/python)
frame #32: <unknown function> + 0xffa68 (0x5586d291fa68 in /home/project/anaconda3/bin/python)
frame #33: _PyEval_EvalCodeWithName + 0x2d2 (0x5586d29aaa92 in /home/project/anaconda3/bin/python)
frame #34: _PyFunction_Vectorcall + 0x1e3 (0x5586d29ab943 in /home/project/anaconda3/bin/python)
frame #35: <unknown function> + 0x7df36 (0x5586d289df36 in /home/project/anaconda3/bin/python)
frame #36: <unknown function> + 0x1001de (0x5586d29201de in /home/project/anaconda3/bin/python)
frame #37: _PyFunction_Vectorcall + 0x10b (0x5586d29ab86b in /home/project/anaconda3/bin/python)
frame #38: <unknown function> + 0x7df36 (0x5586d289df36 in /home/project/anaconda3/bin/python)
frame #39: <unknown function> + 0xffee1 (0x5586d291fee1 in /home/project/anaconda3/bin/python)
frame #40: _PyEval_EvalCodeWithName + 0x2d2 (0x5586d29aaa92 in /home/project/anaconda3/bin/python)
frame #41: PyEval_EvalCodeEx + 0x44 (0x5586d29ab754 in /home/project/anaconda3/bin/python)
frame #42: PyEval_EvalCode + 0x1c (0x5586d2a39edc in /home/project/anaconda3/bin/python)
frame #43: <unknown function> + 0x24f083 (0x5586d2a6f083 in /home/project/anaconda3/bin/python)
frame #44: <unknown function> + 0x140699 (0x5586d2960699 in /home/project/anaconda3/bin/python)
frame #45: <unknown function> + 0x7df36 (0x5586d289df36 in /home/project/anaconda3/bin/python)
frame #46: <unknown function> + 0xffee1 (0x5586d291fee1 in /home/project/anaconda3/bin/python)
frame #47: _PyEval_EvalCodeWithName + 0x2d2 (0x5586d29aaa92 in /home/project/anaconda3/bin/python)
frame #48: _PyFunction_Vectorcall + 0x1e3 (0x5586d29ab943 in /home/project/anaconda3/bin/python)
frame #49: <unknown function> + 0x7df36 (0x5586d289df36 in /home/project/anaconda3/bin/python)
frame #50: <unknown function> + 0xffa68 (0x5586d291fa68 in /home/project/anaconda3/bin/python)
frame #51: _PyFunction_Vectorcall + 0x10b (0x5586d29ab86b in /home/project/anaconda3/bin/python)
frame #52: <unknown function> + 0x7df36 (0x5586d289df36 in /home/project/anaconda3/bin/python)
frame #53: <unknown function> + 0x100066 (0x5586d2920066 in /home/project/anaconda3/bin/python)
frame #54: _PyEval_EvalCodeWithName + 0x2d2 (0x5586d29aaa92 in /home/project/anaconda3/bin/python)
frame #55: _PyFunction_Vectorcall + 0x1e3 (0x5586d29ab943 in /home/project/anaconda3/bin/python)
frame #56: <unknown function> + 0x10075e (0x5586d292075e in /home/project/anaconda3/bin/python)
frame #57: _PyFunction_Vectorcall + 0x10b (0x5586d29ab86b in /home/project/anaconda3/bin/python)
frame #58: <unknown function> + 0xfeb84 (0x5586d291eb84 in /home/project/anaconda3/bin/python)
frame #59: _PyEval_EvalCodeWithName + 0x2d2 (0x5586d29aaa92 in /home/project/anaconda3/bin/python)
frame #60: PyEval_EvalCodeEx + 0x44 (0x5586d29ab754 in /home/project/anaconda3/bin/python)
frame #61: PyEval_EvalCode + 0x1c (0x5586d2a39edc in /home/project/anaconda3/bin/python)
frame #62: <unknown function> + 0x219f84 (0x5586d2a39f84 in /home/project/anaconda3/bin/python)
frame #63: <unknown function> + 0x24c1f4 (0x5586d2a6c1f4 in /home/project/anaconda3/bin/python)
 (function ComputeConstantFolding)
Traceback (most recent call last):
  File "/home/project/anaconda3/lib/python3.8/site-packages/torch/onnx/utils.py", line 724, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/home/project/anaconda3/lib/python3.8/site-packages/torch/onnx/utils.py", line 544, in _model_to_graph
    params_dict = torch._C._jit_pass_onnx_constant_fold(graph, params_dict,
IndexError: index_select(): Index is supposed to be a vector
```

**Comment by GodsDusk** [comment]
solved by https://github.com/oborchers/sentence-transformers/blob/72da7293186700bff4fed8e81adcfe40a03be1d2/examples/onnx_inference/onnx_inference.ipynb

**Comment by unbreading** [comment]
@GodsDusk 

> solved by https://github.com/oborchers/sentence-transformers/blob/72da7293186700bff4fed8e81adcfe40a03be1d2/examples/onnx_inference/onnx_inference.ipynb

Hi，could you share your code ? I met exactly the same problem. Multi-modules in sentence-transformers to onnx is a trouble to me.

**Comment by aeeeeeep** [comment]
Do you know more about this error?  I also encountered this.

**Comment by huanoka** [comment]
> 

Did you pass dynamic_axe to onnx.export? I sloved this when passing it.

**Comment by huanoka** [comment]
> Do you know more about this error? I also encountered this.
Did you pass dynamic_axe to export? I sloved this when passing it.

**Comment by huanoka** [comment]
> Do you know more about this error? I also encountered this.

Did you pass dynamic_axe to export? I sloved this when passing it.

**Comment by aeeeeeep** [comment]
> > Do you know more about this error? I also encountered this.
> 
> Did you pass dynamic_axe to export? I sloved this when passing it.

Thank you for your reply.

Now I have solved this problem, I add `do_constant_folding=False` in `torch.onnx.export`, but there is another problem.

when I use command `trtexec` to export tensorrt from onnx, my model weights are all miss, the accuracy just only `0.02`, although everything went well afterwards.
