### ISSUE TITLE
[ClipModel] Error on PNG images?

### ISSUE THREAD

**Issue by etiennedi** [UKPLab/sentence-transformers#1309]
Thank you very much for integrating CLIP Models into ST. This makes the process extremely convenient. It works great with `JPEG` files, but using a `PNG` image I run into the following error:

```
from sentence_transformers import SentenceTransformer
from PIL import Image

img_model = SentenceTransformer('clip-ViT-B-32')
img = Image.open('./image.png')
res = img_model.encode(img)
```

produces

```
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    res = img_model.encode(img)
  File "/usr/local/lib/python3.8/site-packages/sentence_transformers/SentenceTransformer.py", line 153, in encode
    features = self.tokenize(sentences_batch)
  File "/usr/local/lib/python3.8/site-packages/sentence_transformers/SentenceTransformer.py", line 311, in tokenize
    return self._first_module().tokenize(texts)
  File "/usr/local/lib/python3.8/site-packages/sentence_transformers/models/CLIPModel.py", line 71, in tokenize
    inputs = self.processor(text=texts_values, images=images, return_tensors="pt", padding=True)
  File "/usr/local/lib/python3.8/site-packages/transformers/models/clip/processing_clip.py", line 148, in __call__
    image_features = self.feature_extractor(images, return_tensors=return_tensors, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/transformers/models/clip/feature_extraction_clip.py", line 150, in __call__
    images = [self.normalize(image=image, mean=self.image_mean, std=self.image_std) for image in images]
  File "/usr/local/lib/python3.8/site-packages/transformers/models/clip/feature_extraction_clip.py", line 150, in <listcomp>
    images = [self.normalize(image=image, mean=self.image_mean, std=self.image_std) for image in images]
  File "/usr/local/lib/python3.8/site-packages/transformers/image_utils.py", line 123, in normalize
    image = self.to_numpy_array(image)
  File "/usr/local/lib/python3.8/site-packages/transformers/image_utils.py", line 103, in to_numpy_array
    image = image.transpose(2, 0, 1)
ValueError: axes don't match array
```

Versions used:
```
sentence-transformers==2.1.0
torch==1.10.0
```

Using a JPG image in the same place works fine and creates the desired embeddings.

Is this a limitation of the setup or a bug? Happy to contribute to the solution if you can point us in the right direction.

Thanks!

**Comment by etiennedi** [comment]
I just saw after posting that the stack trace could also imply that this is in happening in the huggingface/transformers instead due to `transformers/models/clip/processing_clip.py`, etc. If this is the wrong repo, please let me know and I'll repost there.

**Comment by etiennedi** [comment]
Update: Trying to do this without SentenceTransformers and huggingface/transformers directly yields the same error:

```
from PIL import Image
import requests

from transformers import CLIPProcessor, CLIPModel

model = CLIPModel.from_pretrained("/path/to/clip/model")
processor = CLIPProcessor.from_pretrained("/path/to/clip/model")

image = Image.open("./image.png")
inputs = processor(images=image, return_tensors="pt", padding=True)

outputs = model(**inputs)

print(outputs)
```

```
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    inputs = processor(images=image, return_tensors="pt", padding=True)
  File "/usr/local/lib/python3.8/site-packages/transformers/models/clip/processing_clip.py", line 148, in __call__
    image_features = self.feature_extractor(images, return_tensors=return_tensors, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/transformers/models/clip/feature_extraction_clip.py", line 150, in __call__
    images = [self.normalize(image=image, mean=self.image_mean, std=self.image_std) for image in images]
  File "/usr/local/lib/python3.8/site-packages/transformers/models/clip/feature_extraction_clip.py", line 150, in <listcomp>
    images = [self.normalize(image=image, mean=self.image_mean, std=self.image_std) for image in images]
  File "/usr/local/lib/python3.8/site-packages/transformers/image_utils.py", line 123, in normalize
    image = self.to_numpy_array(image)
  File "/usr/local/lib/python3.8/site-packages/transformers/image_utils.py", line 103, in to_numpy_array
    image = image.transpose(2, 0, 1)
ValueError: axes don't match array
```

So, I guess I should repost this to https://github.com/huggingface/transformers?

**Comment by etiennedi** [comment]
I dug a bit deeper and this is definitely not related to this repo. However, if someone else comes across this here's how you can fix it:

A PNG image might be in "palette" mode, meaning that instead of having 3 dimensions for RGB, etc. there's a single dimension that specifies which color is used from a palette. This seems to break the image utils in huggingface/transformers. Thus, a very simple workaround (or maybe even a fix?) is the following:

```python
from PIL import Image

img = image.load("./your-png-image-in-palette-mode.png")
if img.mode != 'RGB':
  img=img.convert('RGB')
```

This fixed it for us. Disclaimer: I have no idea how expensive this conversion is. Hope this may help someone else. :-)

**Comment by shibing624** [comment]
good
