### ISSUE TITLE
Sudden ImportError and FileNotFoundError after working for weeks

### ISSUE THREAD

**Issue by Adrizzledefizzle** [UKPLab/sentence-transformers#137]
I am trying to run the sentence-transformer. I was using it for weeks now and suddenly it crashed. I cant even load the models anymore.
It gives me different errormessages.

Code1:
```
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('bert-base-nli-max-tokens')
```
Error1:
```
runfile('C:/Users/ga2943/Documents/Adrian/unbenannt0.py', wdir='C:/Users/ga2943/Documents/Adrian')
100%|██████████| 405M/405M [00:34<00:00, 11.6MB/s] 
Traceback (most recent call last):

  File "<ipython-input-19-447c359facd1>", line 1, in <module>
    runfile('C:/Users/ga2943/Documents/Adrian/unbenannt0.py', wdir='C:/Users/ga2943/Documents/Adrian')

  File "C:\Users\ga2943\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Users\ga2943\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/ga2943/Documents/Adrian/unbenannt0.py", line 9, in <module>
    model = SentenceTransformer('bert-base-nli-max-tokens')

  File "C:\Users\ga2943\AppData\Local\Continuum\anaconda3\lib\site-packages\sentence_transformers\SentenceTransformer.py", line 81, in __init__
    module_class = import_from_string(module_config['type'])

  File "C:\Users\ga2943\AppData\Local\Continuum\anaconda3\lib\site-packages\sentence_transformers\util.py", line 69, in import_from_string
    module = importlib.import_module(module_path)

  File "C:\Users\ga2943\AppData\Local\Continuum\anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)

  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import

  File "<frozen importlib._bootstrap>", line 983, in _find_and_load

  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked

  File "<frozen importlib._bootstrap_external>", line 728, in exec_module

  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "C:\Users\ga2943\AppData\Local\Continuum\anaconda3\lib\site-packages\sentence_transformers\models\__init__.py", line 1, in <module>
    from .ALBERT import ALBERT

  File "C:\Users\ga2943\AppData\Local\Continuum\anaconda3\lib\site-packages\sentence_transformers\models\ALBERT.py", line 3, in <module>
    from transformers import AlbertModel, AlbertTokenizer


ImportError: cannot import name 'AlbertModel' from 'transformers' (C:\Users\ga2943\AppData\Local\Continuum\anaconda3\lib\site-packages\transformers\__init__.py)
```
Code2:
```
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('roberta-large-nli-stsb-mean-tokens')
```
It does not start to download the model but instead gives me this 
Error2:
```
runfile('C:/Users/ga2943/Documents/Adrian/unbenannt0.py', wdir='C:/Users/ga2943/Documents/Adrian')
Traceback (most recent call last):

  File "<ipython-input-22-447c359facd1>", line 1, in <module>
    runfile('C:/Users/ga2943/Documents/Adrian/unbenannt0.py', wdir='C:/Users/ga2943/Documents/Adrian')

  File "C:\Users\ga2943\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Users\ga2943\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/ga2943/Documents/Adrian/unbenannt0.py", line 9, in <module>
    model = SentenceTransformer('bert-large-nli-stsb-mean-tokens')

  File "C:\Users\ga2943\AppData\Local\Continuum\anaconda3\lib\site-packages\sentence_transformers\SentenceTransformer.py", line 76, in __init__
    with open(os.path.join(model_path, 'modules.json')) as fIn:

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ga2943/.cache\\torch\\sentence_transformers\\public.ukp.informatik.tu-darmstadt.de_reimers_sentence-transformers_v0.2_bert-large-nli-stsb-mean-tokens.zip\\modules.json'
```

I put both errors in the same Issue-post, as I am guessing they are related to each other. Why would  it suddenly stop working ? ( It stopped at the beginning of this week, dont know exact day)

Any idea on how to resolve this? If you need more information from my end, please let me know!

Regards,
Adrian

**Comment by nreimers** [comment]
Have you tried re-installing it in a fresh virtual environment?

**Comment by Adrizzledefizzle** [comment]
Yes, nothing changed. I'll do it again right away, letting you know as soon as I'm done. Btw. I did not update or delete anything manually that could have caused the error.

**Comment by Adrizzledefizzle** [comment]
Works like a charm! - Don't know what changed, but works as it used to. Was about to go mad already..

Danke Nils!

**Comment by jbbqqf** [comment]
Hi! Triaging older issues — both errors here are tied to the pre-2.0 model-distribution path that no longer exists.

Evidence:
- Error 1 (`cannot import name 'AlbertModel'`) was fixed in the OP's own follow-up: a fresh virtualenv resolved it. They reported "works like a charm" the same day.
- Error 2 references the legacy zip-download URL (`public.ukp.informatik.tu-darmstadt.de_reimers_sentence-transformers_v0.2_*.zip`). That code path was removed in the 2.x rewrite; models now come from the Hugging Face Hub via `huggingface_hub`. The current loader is at [`sentence_transformers/sentence_transformer/SentenceTransformer.py`](https://github.com/huggingface/sentence-transformers/blob/master/sentence_transformers/sentence_transformer/SentenceTransformer.py) and goes through `snapshot_download`, not the UKP zip mirror.
- The model id used (`roberta-large-nli-stsb-mean-tokens`) is still resolvable today via `sentence-transformers/roberta-large-nli-stsb-mean-tokens` on the Hub: [link](https://huggingface.co/sentence-transformers/roberta-large-nli-stsb-mean-tokens).

If a similar `FileNotFoundError` still surfaces on a modern `sentence-transformers >= 5.x` install, it'd be worth a fresh issue with the current traceback. Otherwise this one is closeable.

---
*Disclosure: I drafted this triage comment with help from Claude Code while going through stale issues; the references above were verified manually against current `master`.*
