### ISSUE TITLE
Can't pip install. Error: metadata-generation-failed

### ISSUE THREAD

**Issue by TheRealPolatic** [UKPLab/sentence-transformers#1443]
When try to install sentence-transformer, it gives me the the following error.
My python version: 3.10.2
My pip version: 22.0.3
OS: Windows 10

```error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\USER\AppData\Local\Temp\pip-install-716a0137\sentence-transformers_312e10fa437644fe9cb8501fc1b91ee9\setup.py", line 6, in <module>
          with open('requirements.txt', mode="r", encoding="utf-8") as req_file:
      FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.```

**Comment by TheRealPolatic** [comment]
Turned out my python version was too new. I downgraded to 3.9.9 and it worked fine after that.

**Comment by mynameis-sohee** [comment]
> Turned out my python version was too new. I downgraded to 3.9.9 and it worked fine after that.

solved thanks to you !!! Thank you 👍
