### ISSUE TITLE
Issues installing the all-MiniLM-L6-v2 model

### ISSUE THREAD

**Issue by Tawnwen** [UKPLab/sentence-transformers#1462]
I have a Dockerized web app that uses pre-trained models. Due to network constrains, I am required to save the models locally. I download them from https://public.ukp.informatik.tu-darmstadt.de/reimers/sentence-transformers/v0.2/ and save the model in a /sent_bert directory.  

**Successfully in the past** I've done this via:
```
wget --no-check-certificate https://public.ukp.informatik.tu-darmstadt.de/reimers/sentence-transformers/v0.2/distilbert-base-nli-stsb-mean-tokens.zip
unzip distilbert-base-nli-stsb-mean-tokens.zip -d ./sent_bert
```

And then in Python:
```
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('./sent_bert')
```

Recently I've tried to update to use the **all-MiniLM-L6-v2** model instead. I simply replaced distilbert-base-nli-stsb-mean-tokens with all-MiniLM-L6-v2 in my Dockerfile and everything builds nicely. However, when Python executes `model = SentenceTransformer('./sent_bert')` I get this error:

```
Traceback (most recent call last):
File "/usr/src/app/py/req_matcher.py", line 38, in <module>
import acronyms.acronym_expansion as AE

File "/usr/src/app/py/acronyms/acronym_expansion.py", line 39, in <module>
model = SentenceTransformer(os.path.join(cur_file_path, '../sent_bert')) #model = embedder in sentence_bert.py

File "/root/.local/lib/python3.8/site-packages/sentence_transformers/SentenceTransformer.py", line 112, in __init__

if config['__version__'] > __version__:

KeyError: '__version__'
``` 

[Research](https://github.com/UKPLab/sentence-transformers/issues/371) implies I need to specifically import the new model like this:

```
from sentence_transformers import SentenceTransformer

model = SentenceTransformer('all-MiniLM-L6-v2')
model.save('./sent_bert/')
```

However, again, this results in a urllib3 SSLCertVerificationError due to my network constraints, much like in this issue [here](https://github.com/UKPLab/sentence-transformers/issues/571).

Is there a way to fix this? I cannot use `model = SentenceTransformer('all-MiniLM-L6-v2')` due to SSLCertVerificationError / network constraints and I cannot import the model from local files using `model = SentenceTransformer('./sent_bert')` due to the KeyError above.

**Comment by nreimers** [comment]
Which version of sentence-transformers are you using?
