### ISSUE TITLE
sentence-transformers/parallel-sentences broken

### ISSUE THREAD

**Issue by muelletm** [UKPLab/sentence-transformers#1509]
Not sure if this is the best place to report this but when running:

```python
from datasets import load_dataset

dataset = load_dataset("sentence-transformers/parallel-sentences")
```

I get an error:

```
Traceback (most recent call last):
  File ".../lib/python3.8/site-packages/datasets/packaged_modules/csv/csv.py", line 156, in _generate_tables
    for batch_idx, df in enumerate(csv_file_reader):
  File ".../lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1187, in __next__
    return self.get_chunk()
  File ".../lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1284, in get_chunk
    return self.read(nrows=size)
  File ".../lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1254, in read
    index, columns, col_dict = self._engine.read(nrows)
  File ".../lib/python3.8/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 225, in read
    chunks = self._reader.read_low_memory(nrows)
  File "pandas/_libs/parsers.pyx", line 817, in pandas._libs.parsers.TextReader.read_low_memory
  File "pandas/_libs/parsers.pyx", line 861, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 847, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1960, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 9, saw 2
```

It's fixable by passing `sep="\t"` to `load_dataset` but later it still fails with:

```
Traceback (most recent call last):
  File ".../lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File ".../lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/data/research/users/tmueller/projects/CharEmbeddingModel/char_embed/cli.py", line 19, in <module>
    app()
  File ".../lib/python3.8/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File ".../lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File ".../lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File ".../lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File ".../lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File ".../lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File ".../lib/python3.8/site-packages/typer/main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "/data/research/users/tmueller/projects/CharEmbeddingModel/char_embed/cli.py", line 10, in create_data
    create_data()
  File "/data/research/users/tmueller/projects/CharEmbeddingModel/char_embed/data.py", line 5, in create_data
    dataset = load_dataset("sentence-transformers/parallel-sentences", sep="\t")
  File ".../lib/python3.8/site-packages/datasets/load.py", line 1687, in load_dataset
    builder_instance.download_and_prepare(
  File ".../lib/python3.8/site-packages/datasets/builder.py", line 605, in download_and_prepare
    self._download_and_prepare(
  File ".../lib/python3.8/site-packages/datasets/builder.py", line 694, in _download_and_prepare
    self._prepare_split(split_generator, **prepare_split_kwargs)
  File ".../lib/python3.8/site-packages/datasets/builder.py", line 1154, in _prepare_split
    writer.write_table(table)
  File ".../lib/python3.8/site-packages/datasets/arrow_writer.py", line 508, in write_table
    pa_table = table_cast(pa_table, self._schema)
  File ".../lib/python3.8/site-packages/datasets/table.py", line 1858, in table_cast
    return cast_table_to_schema(table, schema)
  File ".../lib/python3.8/site-packages/datasets/table.py", line 1840, in cast_table_to_schema
    raise ValueError(f"Couldn't cast\n{table.schema}\nto\n{features}\nbecause column names don't match")
ValueError: Couldn't cast
Action taken on Parliament's resolutions: see Minutes: string
Následný postup na základě usnesení Parlamentu: viz zápis: string
-- schema metadata --
pandas: '{"index_columns": [{"kind": "range", "name": null, "start": 0, "' + 742
to
{'Membership of Parliament: see Minutes': Value(dtype='string', id=None), 'Състав на Парламента: вж. протоколи': Value(dtype='string', id=None)}
because column names don't match
```

I am using these versions:

```
Python 3.8.13 (conda)
datasets==2.0.0
pandas==1.4.2
pyarrow==7.0.0
````

**Comment by nreimers** [comment]
You cannot load the dataset with load_dataset, you have to download the files from the git. See the examples how to make embedding models multilingual how to use these files

**Comment by muelletm** [comment]
I see, thanks for the quick response!

Does it make sense to highlight this in the README?

Currently it's a bit misleading since there is the "use in dataset library button".

**Comment by nreimers** [comment]
This button is sadly automatically added. I updated the readme
