### ISSUE TITLE
Issue with loading CLIP model when using transformers==4.18.0

### ISSUE THREAD

**Issue by davidmezzetti** [UKPLab/sentence-transformers#1515]
Hello,

The following issue is encountered when using transformers==4.18.0 with sentence-transformers==2.2.0

```
>>> SentenceTransformer("sentence-transformers/clip-ViT-B-32")
ftfy or spacy is not installed using BERT BasicTokenizer instead of ftfy.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lib/python3.7/site-packages/sentence_transformers/SentenceTransformer.py", line 94, in __init__
    modules = self._load_sbert_model(model_path)
  File "/lib/python3.7/site-packages/sentence_transformers/SentenceTransformer.py", line 831, in _load_sbert_model
    module = module_class.load(os.path.join(model_path, module_config['path']))
  File "/lib/python3.7/site-packages/sentence_transformers/models/CLIPModel.py", line 82, in load
    return CLIPModel(model_name=input_path)
  File "/lib/python3.7/site-packages/sentence_transformers/models/CLIPModel.py", line 15, in __init__
    self.processor = transformers.CLIPProcessor.from_pretrained(processor_name)
  File "/lib/python3.7/site-packages/transformers/processing_utils.py", line 186, in from_pretrained
    args = cls._get_arguments_from_pretrained(pretrained_model_name_or_path, **kwargs)
  File "/lib/python3.7/site-packages/transformers/processing_utils.py", line 230, in _get_arguments_from_pretrained
    args.append(attribute_class.from_pretrained(pretrained_model_name_or_path, **kwargs))
  File "/lib/python3.7/site-packages/transformers/tokenization_utils_base.py", line 1787, in from_pretrained
    **kwargs,
  File "/lib/python3.7/site-packages/transformers/tokenization_utils_base.py", line 1915, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/lib/python3.7/site-packages/transformers/models/clip/tokenization_clip_fast.py", line 95, in __init__
    **kwargs,
  File "/lib/python3.7/site-packages/transformers/tokenization_utils_fast.py", line 109, in __init__
    fast_tokenizer = TokenizerFast.from_file(fast_tokenizer_file)
Exception: No such file or directory (os error 2)
```

The same error is found when using the path `clip-ViT-B-32`. This doesn't occur with transformers < 4.18.0, so it's entirely possible it's an upstream transformers issue but I wanted to get your opinion first. It looks like it works fine with `sentence-transformers/clip-ViT-B-32-multilingual-v1`.

Appreciate the help.

**Comment by davidmezzetti** [comment]
It appears this issue is caused by the file [0_CLIPModel/tokenizer_config.json](https://huggingface.co/sentence-transformers/clip-ViT-B-32/raw/main/0_CLIPModel/tokenizer_config.json) having a tokenizer_file path set.

```json
"tokenizer_file": "/home/ukp-reimers/.cache/huggingface/transformers/7811def0c53be25ba790cb67ac785669b508a8d1cf8c912b8ac046c5f08aee68.c51a626c1dc62de865745e4ab7125f190823b458ac5ee9ce21b1d006512b3a53"
```

If I do a snapshot download of the model and manually remove that line, everything works as expected with transformers==4.18.0. 

Perhaps the model can be updated on the hub to remove that line? There is also a similar line for special_tokens_map_file but that doesn't appear to cause an issue right now.

**Comment by nreimers** [comment]
Thanks for reporting and finding the issue.

I updated the model. It works for me. Can you check if it also works for you? You might need to first remove the files from the cache so that the model is downloaded again

**Comment by davidmezzetti** [comment]
Thank you @nreimers, I tested it and everything works! I'll go ahead and close this. Thanks again.
