### ISSUE TITLE
how can I using intel_extension_for_pytorch in sentence_transformers

### ISSUE THREAD

**Issue by WanBenLe** [UKPLab/sentence-transformers#1555]
The example in https://pytorch.org/tutorials/recipes/recipes/intel_extension_for_pytorch.html is :
```
import torch
import torch.nn as nn
# Import intel_extension_for_pytorch
import intel_extension_for_pytorch as ipex

class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.linear = nn.Linear(4, 5)

    def forward(self, input):
        return self.linear(input)

model = Model()
model.set_state_dict(torch.load(PATH))
optimizer.set_state_dict(torch.load(PATH))
# Invoke optimize function against the model object and optimizer object
model, optimizer = ipex.optimize(model, optimizer, dtype=torch.float32)

for images, label in train_loader():
    # Setting memory_format to torch.channels_last could improve performance with 4D input data. This is optional.
    images = images.to(memory_format=torch.channels_last)
    loss = criterion(model(images), label)
    loss.backward()
    optimizer.step()
torch.save(model.state_dict(), PATH)
torch.save(optimizer.state_dict(), PATH)
```

I try to change the def fit() in **sentence_transformers/SentenceTransformer.py**
```

optimizer = optimizer_class(optimizer_grouped_parameters, **optimizer_params)


print('train')#this
loss_model, optimizer = ipex.optimize(loss_model, optimizer)#this

scheduler_obj = self._get_scheduler(optimizer, scheduler=scheduler, warmup_steps=warmup_steps, t_total=num_train_steps)

optimizers.append(optimizer)
schedulers.append(scheduler_obj)


```
and load pretrain model and train in new sample will return error :
Traceback (most recent call last):
  File "step1hedanzhunbei.py", line 56, in <module>
    model.fit(train_objectives=[(train_dataloader, train_loss)], epochs=10, show_progress_bar=True)
  File "/opt/intel/oneapi/intelpython/latest/envs/idp3.8/lib/python3.8/site-packages/sentence_transformers/SentenceTransformer.py", line 667, in fit
    loss_model, optimizer = ipex.optimize(loss_model, optimizer)
  File "/opt/intel/oneapi/intelpython/latest/envs/idp3.8/lib/python3.8/site-packages/intel_extension_for_pytorch/frontend.py", line 204, in optimize
    assert optimizer is not None, "The optimizer should be given for training mode"
AssertionError: The optimizer should be given for training mode

How can I fix it?

**Comment by ramashisx** [comment]
put model.train() on the top of the loop
