### ISSUE TITLE
0.2.6 should be yanked on pypi

### ISSUE THREAD

**Issue by bra-fsn** [UKPLab/sentence-transformers#1616]
When I try to install a big enough `requirements.txt`, it dies on `sentence-transformers` with the error of:
```
Collecting sentence-transformers==0.2.6
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-mby1wh7b/sentence-transformers_6e648f31f43940e9be1da0ada44ae33b/setup.py", line 6, in <module>
          with open('requirements.txt', mode="r", encoding="utf-8") as req_file:
      FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

When I try to install this exact version I get the same error, which is fixed by this commit:
https://github.com/UKPLab/sentence-transformers/commit/203c32e48f28d5ecdd81bab5f55e02d56a638347
but because `0.2.6` wasn't yanked, pip may be looking at it during its dependency resolution process, breaking the install.

So please, yank (if that's enough for `pip` to skip it during its conflict resolution, I'm not sure about that) or delete this version .

**Comment by nreimers** [comment]
Thanks, I yanked the version
