### ISSUE TITLE
Can't download model from ZIP URL]

### ISSUE THREAD

**Issue by NicolaiSchmid** [UKPLab/sentence-transformers#1815]
```
import os
from sentence_transformers import SentenceTransformer

SentenceTransformer('https://modelstoremanual.blob.core.windows.net/models/Cosma_2023-01-20_lowercase.zip')
```
Throws this error

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/sentence_transformers/SentenceTransformer.py", line 77, in __init__
      raise ValueError("Path {} not found".format(model_name_or_path))
         ValueError: Path https://modelstoremanual.blob.core.windows.net/models/Cosma_2023-01-20_lowercase.zip not found
```

Looking at the implementation https://github.com/UKPLab/sentence-transformers/blob/master/sentence_transformers/SentenceTransformer.py#L76 I don't really see how loading a model from a URL as zip would work, since all https:// paths would be handled before it reaches the download code
(https://sbert.net/docs/training/overview.html?highlight=zip#loading-custom-sentencetransformer-models)

**Comment by bm777** [comment]
Hi @NicolaiSchmid, you can simply download the zip, and then load it from your storage.
`model = SentenceTransformer('./my/path/to/model/')`

**Note:** It is important that a / or \ is present in the path, otherwise, it is not recognized as a path.

**Comment by NicolaiSchmid** [comment]
Yes, that's the workaround I'm using now, but it's rather annoying and at least shouldn't be documented anymore

**Comment by kaushikacharya** [comment]
> Hi [@NicolaiSchmid](https://github.com/NicolaiSchmid), you can simply download the zip, and then load it from your storage. `model = SentenceTransformer('./my/path/to/model/')`
> 
> **Note:** It is important that a / or \ is present in the path, otherwise, it is not recognized as a path.

Loading model from local zip file won't work now.
This is because https://github.com/UKPLab/sentence-transformers/blob/82fa8415b60f85ffb30e8d29353e40bd8fd1bafc/sentence_transformers/SentenceTransformer.py#L301 
would fail as https://github.com/UKPLab/sentence-transformers/blob/82fa8415b60f85ffb30e8d29353e40bd8fd1bafc/sentence_transformers/util.py#L1319 expects `modules.json` in `model_name_or_path` directory.
