### ISSUE TITLE
Question about "train_stsbenchmark.py"

### ISSUE THREAD

**Issue by chenchuming** [UKPLab/sentence-transformers#1834]
I am testing "train_stsbenchmark.py" with huggingface transformer "Rostlab/prot_t5_xl_uniref50" and get the following error. What am I missing? How do I fix it? Thanks.

$ python train_stsbenchmark.py Rostlab/prot_t5_xl_uniref50

Some weights of the model checkpoint at Rostlab/prot_t5_xl_uniref50 were not used when initializing T5EncoderModel: ['lm_head.weight']
- This IS expected if you are initializing T5EncoderModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing T5EncoderModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Traceback (most recent call last):
  File "/data/home/chenc/train_stsbenchmark.py", line 49, in <module>
    word_embedding_model = models.Transformer(model_name)
  File "/home/chenc/anaconda3/lib/python3.9/site-packages/sentence_transformers/models/Transformer.py", line 31, in __init__
    self.tokenizer = AutoTokenizer.from_pretrained(tokenizer_name_or_path if tokenizer_name_or_path is not None else model_name_or_path, cache_dir=cache_dir, **tokenizer_args)
  File "/home/chenc/anaconda3/lib/python3.9/site-packages/transformers/models/auto/tokenization_auto.py", line 637, in from_pretrained
    return tokenizer_class_fast.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/home/chenc/anaconda3/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 1777, in from_pretrained
    return cls._from_pretrained(
  File "/home/chenc/anaconda3/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 1932, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/home/chenc/anaconda3/lib/python3.9/site-packages/transformers/models/t5/tokenization_t5_fast.py", line 134, in __init__
    super().__init__(
  File "/home/chenc/anaconda3/lib/python3.9/site-packages/transformers/tokenization_utils_fast.py", line 114, in __init__
    fast_tokenizer = convert_slow_tokenizer(slow_tokenizer)
  File "/home/chenc/anaconda3/lib/python3.9/site-packages/transformers/convert_slow_tokenizer.py", line 1162, in convert_slow_tokenizer
    return converter_class(transformer_tokenizer).converted()
  File "/home/chenc/anaconda3/lib/python3.9/site-packages/transformers/convert_slow_tokenizer.py", line 500, in converted
    tokenizer = self.tokenizer(self.proto)
  File "/home/chenc/anaconda3/lib/python3.9/site-packages/transformers/convert_slow_tokenizer.py", line 478, in tokenizer
    raise Exception(
Exception: You're trying to run a `Unigram` model but you're file was trained with a different algorithm

**Comment by buegelbeatz** [comment]
For me it works with T5Tokenizer and T5EncoderModel class - But don't ask why? Got also no answer so far

**Comment by tomaarsen** [comment]
In the case of @chenchuming, it seems that there's an issue with loading the tokenizer of the `Rostlab/prot_t5_xl_uniref50` model. This code gives the same error:
```python
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("Rostlab/prot_t5_xl_uniref50")
```

- Tom Aarsen

**Comment by buegelbeatz** [comment]
Have you tried the T5Tokenizer to load it?
