### ISSUE TITLE
OSError: Unable to load weights from pytorch checkpoint file

### ISSUE THREAD

**Issue by zhouchunpong** [UKPLab/sentence-transformers#2455]
python 3.8
torch 1.9
transformers  4.37.1

model = SentenceTransformer('all-roberta-large-v1', device=f'cuda:{args.gpu}')

    unpickler = UnpicklerWrapper(data_file, **pickle_load_args)                                   
TypeError: 'weights_only' is an invalid keyword argument for Unpickler()                          
                                                                                                  
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zcp/anaconda3/envs/prompt/lib/python3.8/site-packages/transformers/modeling_utils.py
", line 542, in load_state_dict
    if f.read(7) == "version":
  File "/home/zcp/anaconda3/envs/prompt/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 64: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_metav11KDbert.py", line 721, in <module>
    main(args)
  File "train_metav11KDbert.py", line 127, in main
    teacher = SentenceTransformer('paraphrase-TinyBERT-L6-v2', device=f'cuda:{args.gpu}')
  File "/home/zcp/anaconda3/envs/prompt/lib/python3.8/site-packages/sentence_transformers/SentenceTransformer.py", line 95, in __init__
    modules = self._load_sbert_model(model_path)
  File "/home/zcp/anaconda3/envs/prompt/lib/python3.8/site-packages/sentence_transformers/Sentence
Transformer.py", line 840, in _load_sbert_model
    module = module_class.load(os.path.join(model_path, module_config['path']))
  File "/home/zcp/anaconda3/envs/prompt/lib/python3.8/site-packages/sentence_transformers/models/T
ransformer.py", line 137, in load
    return Transformer(model_name_or_path=input_path, **config)
  File "/home/zcp/anaconda3/envs/prompt/lib/python3.8/site-packages/sentence_transformers/models/T
ransformer.py", line 29, in __init__                             
    self._load_model(model_name_or_path, config, cache_dir)
  File "/home/zcp/anaconda3/envs/prompt/lib/python3.8/site-packages/sentence_transformers/models/T
ransformer.py", line 49, in _load_model
    self.auto_model = AutoModel.from_pretrained(model_name_or_path, config=config, cache_dir=cache
_dir)
  File "/home/zcp/anaconda3/envs/prompt/lib/python3.8/site-packages/transformers/models/auto/auto_
factory.py", line 566, in from_pretrained
    return model_class.from_pretrained(
  File "/home/zcp/anaconda3/envs/prompt/lib/python3.8/site-packages/transformers/modeling_utils.py
", line 3527, in from_pretrained
    state_dict = load_state_dict(resolved_archive_file)
  File "/home/zcp/anaconda3/envs/prompt/lib/python3.8/site-packages/transformers/modeling_utils.py
", line 554, in load_state_dict
    raise OSError(
OSError: Unable to load weights from pytorch checkpoint file for '/home/zcp/.cache/torch/sentence_
transformers/sentence-transformers_paraphrase-TinyBERT-L6-v2/pytorch_model.bin' at '/home/zcp/.cac
he/torch/sentence_transformers/sentence-transformers_paraphrase-TinyBERT-L6-v2/pytorch_model.bin'.
 If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.

**Comment by tomaarsen** [comment]
Hello!

I'm able to reproduce this with your provided dependencies - and was able to resolve it by upgrading `torch` to `1.13.0`. You can also upgrade it much further, to e.g. `2.1.0` - that's where I personally have it.

- Tom Aarsen

**Comment by skywindy** [comment]
hello ,
but my computer only support cuda11.3 ,so i can only  upgrading torch to 1.12.1,how can i fix this problem?

**Comment by tomaarsen** [comment]
Hello,

You can try increasing the `transformers` version, which might work. Also, if the model that you're loading has a `model.safetensors` file, then make sure that you have `safetensors` installed: then you won't have to use the `torch` load (which is what seems to be going wrong for you).

- Tom Aarsen
