### ISSUE TITLE
V2.3.0 download misses `config.json` 

### ISSUE THREAD

**Issue by michaelfeil** [UKPLab/sentence-transformers#2456]
It seems to me like only a fraction of files is downloaded at first -  seems okay so far. Afterwards, the `config.json` is searched, but not found in the already downloaded files. 

Here are some of the steps to reproduce this.

1. Clean up all files in the cache
```bash
rm ~/.cache/huggingface/hub/ -rf
```
2. start the model
```python
>>> from sentence_transformers import SentenceTransformer
>>> SentenceTransformer("BAAI/bge-small-en-v1.5")
modules.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 349/349 [00:00<00:00, 2.34MB/s]
config_sentence_transformers.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 124/124 [00:00<00:00, 645kB/s]
README.md: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 90.3k/90.3k [00:00<00:00, 1.37MB/s]
sentence_bert_config.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 52.0/52.0 [00:00<00:00, 415kB/s]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/michael/embeddings/infinity/libs/infinity_emb/.venv/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py", line 194, in __init__
    modules = self._load_sbert_model(
  File "/home/michael/embeddings/infinity/libs/infinity_emb/.venv/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py", line 1060, in _load_sbert_model
    module = Transformer(model_name_or_path, cache_dir=cache_folder, **kwargs)
  File "/home/michael/embeddings/infinity/libs/infinity_emb/.venv/lib/python3.10/site-packages/sentence_transformers/models/Transformer.py", line 35, in __init__
    config = AutoConfig.from_pretrained(model_name_or_path, **model_args, cache_dir=cache_dir)
  File "/home/michael/embeddings/infinity/libs/infinity_emb/.venv/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 1082, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/michael/embeddings/infinity/libs/infinity_emb/.venv/lib/python3.10/site-packages/transformers/configuration_utils.py", line 644, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/michael/embeddings/infinity/libs/infinity_emb/.venv/lib/python3.10/site-packages/transformers/configuration_utils.py", line 699, in _get_config_dict
    resolved_config_file = cached_file(
  File "/home/michael/embeddings/infinity/libs/infinity_emb/.venv/lib/python3.10/site-packages/transformers/utils/hub.py", line 360, in cached_file
    raise EnvironmentError(
OSError: BAAI/bge-small-en-v1.5 does not appear to have a file named config.json. Checkout 'https://huggingface.co/BAAI/bge-small-en-v1.5/None' for available files.
>>> from sentence_transformers import __version__
>>> __version__
'2.3.0'
```

Here is the files downloaded

```bash
ls ~/.cache/huggingface/hub/models--BAAI--bge-small-en-v1.5/snapshots/c202d20b1417db2e392c8aad36b6056867218dce/
README.md  config_sentence_transformers.json  modules.json  sentence_bert_config.json
```

**Comment by michaelfeil** [comment]
I am closing this, as I most likley messed up the config.json with a self-written ctranslate2 integration. My bad.

**Comment by michaelfeil** [comment]
Definetly a hack from my side that is no longer working - I was patching some ct2 files in the repo. The downloads work as intended, just not if you have the model partially downloaded in your local path.
