### ISSUE TITLE
Pip install error: subprocess-exited-with-error

### ISSUE THREAD

**Issue by Fitmavincent** [UKPLab/sentence-transformers#2472]
Detail error from pip install output:
```  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [31 lines of output]
      Traceback (most recent call last):
        File "D:\...\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "D:\...\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "D:\...\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\...\AppData\Local\Temp\pip-build-env-6a9dk5a2\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, 
requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\...\AppData\Local\Temp\pip-build-env-6a9dk5a2\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\...\AppData\Local\Temp\pip-build-env-6a9dk5a2\overlay\Lib\site-packages\setuptools\build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "C:\...\AppData\Local\Temp\pip-build-env-6a9dk5a2\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 126, in <module>
        File "C:\Python3\Lib\subprocess.py", line 408, in check_call
          retcode = call(*popenargs, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Python3\Lib\subprocess.py", line 389, in call
          with Popen(*popenargs, **kwargs) as p:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Python3\Lib\subprocess.py", line 1026, in 
__init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "C:\Python3\Lib\subprocess.py", line 1538, in 
_execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      FileNotFoundError: [WinError 2] The system cannot find the file specified
      [end of output]
```

Python environment detail:
Python 3.12.1
pip 24.0
torch 2.2.0
transformers 4.37.2

OS version: Win 10
NVCC version: 
Cuda compilation tools, release 12.1, V12.1.66
Build cuda_12.1.r12.1/compiler.32415258_0

**Comment by tomaarsen** [comment]
Hello!

I'm getting reports that this is due to `sentencepiece` not being supported by Python 3.12 yet. Now, I believe that `sentencepiece` is an optional dependency, so you can hopefully get around this using:
```
pip install tqdm torch numpy transformers scikit-learn scipy nltk huggingface-hub>=0.15.1 Pillow
pip install sentence-transformers --no-deps
```
Please let me know if this works if you get around to testing it!

- Tom Aarsen

**Comment by Fitmavincent** [comment]
> Hello!
> 
> I'm getting reports that this is due to `sentencepiece` not being supported by Python 3.12 yet. Now, I believe that `sentencepiece` is an optional dependency, so you can hopefully get around this using:
> 
> ```
> pip install tqdm torch numpy transformers scikit-learn scipy nltk huggingface-hub>=0.15.1 Pillow
> pip install sentence-transformers --no-deps
> ```
> 
> Please let me know if this works if you get around to testing it!
> 
> * Tom Aarsen

Thank you Tom. It works for me with your suggested get around. Thank you.
