### ISSUE TITLE
Error when loading INSTRUCTOR model

### ISSUE THREAD

**Issue by Fitmavincent** [UKPLab/sentence-transformers#2474]
When I try to load INSTRUCTOR model:
```
INSTRUCTOR._load_sbert_model() got an unexpected keyword argument 'token'
```

Error detail:
```
Traceback (most recent call last):
  File "D:\...\main.py", line 28, in <module>
    model = INSTRUCTOR('hkunlp/instructor-large')
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\...\venv\Lib\site-packages\sentence_transformers\SentenceTransformer.py", line 194, in __init__
    modules = self._load_sbert_model(
              ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: INSTRUCTOR._load_sbert_model() got an unexpected keyword argument 'token'
```

I found this issued that raised before and it seems to be resolved by downgrading the `sentence-transformers` to `2.2.2`;
[INSTRUCTOR._load_sbert_model() got an unexpected keyword argument 'token'](https://github.com/PromtEngineer/localGPT/issues/722)

However, this does not seem to work for me as I'm in Python 3.12.2. When I downgraded to `2.2.2`, I got error of `No module named distutils`
[The code that imports distutils will no longer work from Python 3.12.](https://orcacore.com/fix-module-notfound-distutils/)

Python environment detail:
Python 3.12.1
pip 24.0
torch 2.2.0
transformers 4.37.2

OS version: Win 10
NVCC version:
Cuda compilation tools, release 12.1, V12.1.66
Build cuda_12.1.r12.1/compiler.32415258_0

**Comment by tomaarsen** [comment]
Hello!

[INSTRUCTOR](https://github.com/xlang-ai/instructor-embedding) is indeed only compatible with Sentence Transformers 2.2.2, as it overrides some behind-the-scenes functionality that was updated in Sentence Transformers 2.3.0. Perhaps in the future I can try and support INSTRUCTOR models in Sentence Transformers directly.

- Tom Aarsen

**Comment by Fitmavincent** [comment]
Hmm... it sounds like there's no get-around in this one. Thanks for your prompt reply on this issue.

**Comment by jxmai** [comment]
Note that reverting sentence transformer to 2.2.2 workaround may not be applicable in the future. The timing should be approximately after **langchain 1.0 release**.

Reason:

https://api.python.langchain.com/en/latest/_modules/langchain_community/llms/huggingface_pipeline.html#HuggingFacePipeline

![image](https://github.com/user-attachments/assets/537192e8-a841-4f0c-9682-fd75d7ad020a)

The huggingfacePineline provided by langchain is deprecated and will be removed in v1.0

However, the alternative-import: https://api.python.langchain.com/en/latest/llms/langchain_huggingface.llms.huggingface_pipeline.HuggingFacePipeline.html

requires at least v2.6.0 sentence transformer, with v2.2.2, there will be errors

```
langchain-huggingface 0.0.3 requires sentence-transformers>=2.6.0, but you have sentence-transformers 2.2.2 which is incompatible.
```

**Comment by JoyLinWQ** [comment]
Has above been fixed? I'm encountering below error:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
langchain-huggingface 0.1.2 requires sentence-transformers>=2.6.0, but you have sentence-transformers 2.2.2 which is incompatible.

lib\site-packages\sentence_transformers\SentenceTransformer.py", line 12, in <module>
    from huggingface_hub import HfApi, HfFolder, Repository, hf_hub_url, cached_download
ImportError: cannot import name 'cached_download' from 'huggingface_hub'
```

Unable to run with either sentence-transformers==2.2.2 or 2.6.0. 
v2.2.2 gives `cached_download` error, which, if replaced with `hf_hub_download` (as advised (here)<https://github.com/easydiffusion/easydiffusion/issues/1851>, gives other missing function variables in the sentence_transformers/util.py file. Reason is hf_hub_download() is available only in later versions of sentence-transformers)

Also unable to downgrade langchain-huggingface as the earliest versions (even 0.0.1) requires sentence-transformers>=2.6.0.

How to proceed next? Please help.

**Comment by JoyLinWQ** [comment]
Update: This works to properly load the embeddings - https://github.com/UKPLab/sentence-transformers/issues/2523

```
from huggingface_hub import hf_hub_download

path = hf_hub_download("sentence-transformers/all-MiniLM-L6-v2", filename="config.json")
print(path)
```
