### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by ZHAOFEGNSHUN** [UKPLab/sentence-transformers#2645]
Traceback (most recent call last):
  File "/nfs/XLNet/XLNet/xlnet_similarity.py", line 49, in <module>
    model.fit(
  File "/home/luban/.conda/envs/my/lib/python3.9/site-packages/sentence_transformers/SentenceTransformer.py", line 1075, in fit
    data = next(data_iterator)
  File "/home/luban/.conda/envs/my/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/home/luban/.conda/envs/my/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 721, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/luban/.conda/envs/my/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "/home/luban/.conda/envs/my/lib/python3.9/site-packages/sentence_transformers/SentenceTransformer.py", line 908, in smart_batching_collate
    sentence_features = [self.tokenize(sentence) for sentence in zip(*texts)]
  File "/home/luban/.conda/envs/my/lib/python3.9/site-packages/sentence_transformers/SentenceTransformer.py", line 908, in <listcomp>
    sentence_features = [self.tokenize(sentence) for sentence in zip(*texts)]
  File "/home/luban/.conda/envs/my/lib/python3.9/site-packages/sentence_transformers/SentenceTransformer.py", line 592, in tokenize
    return self._first_module().tokenize(texts, **kwargs)
  File "/home/luban/.conda/envs/my/lib/python3.9/site-packages/sentence_transformers/models/Transformer.py", line 146, in tokenize
    self.tokenizer(
  File "/home/luban/.conda/envs/my/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 2858, in __call__
    encodings = self._call_one(text=text, text_pair=text_pair, **all_kwargs)
  File "/home/luban/.conda/envs/my/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 2944, in _call_one
    return self.batch_encode_plus(
  File "/home/luban/.conda/envs/my/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 3135, in batch_encode_plus
    return self._batch_encode_plus(
  File "/home/luban/.conda/envs/my/lib/python3.9/site-packages/transformers/tokenization_utils_fast.py", line 496, in _batch_encode_plus
    self.set_truncation_and_padding(
  File "/home/luban/.conda/envs/my/lib/python3.9/site-packages/transformers/tokenization_utils_fast.py", line 451, in set_truncation_and_padding
    self._tokenizer.enable_truncation(**target)
OverflowError: can't convert negative int to unsigned

what happend?how to slove?

**Comment by tomaarsen** [comment]
Hello!

That is a bit of an odd error. It's trying to do tokenization via `transformers` (and `tokenizers`?), but failing with an error that I've not seen before. I see someone else has gotten a similar issue once: https://github.com/aub-mind/arabert/discussions/129

You can try the following:
```python
from transformers import AutoTokenizer
from sentence_transformers import SentenceTransformer

model_name = "my_model"
model = SentenceTransformer(model_name)
model[0].tokenizer = AutoTokenizer.from_pretrained(model_name, use_fast=False)

model.fit("...")
```

This no longer uses `tokenizers` (which I suspect is where the issue originates), but a Python-based tokenizer instead. 

- Tom Aarsen

**Comment by ZHAOFEGNSHUN** [comment]
We need to remove 11 to truncate the input but the first sequence has a length 8.
We need to remove 14 to truncate the input but the first sequence has a length 11.
We need to remove 14 to truncate the input but the first sequence has a length 11.
                                                                                                                                                                                                                               We need to remove 7 to truncate the input but the first sequence has a length 4. ██████████████████████████████████████████████████████████████████████████████████▌                             | 5/6 [00:00<00:00,  5.38it/s]
We need to remove 14 to truncate the input but the first sequence has a length 11.
We need to remove 12 to truncate the input but the first sequence has a length 9.
We need to remove 14 to truncate the input but the first sequence has a length 11.
We need to remove 13 to truncate the input but the first sequence has a length 10.
We need to remove 10 to truncate the input but the first sequence has a length 7.
We need to remove 23 to truncate the input but the first sequence has a length 20.
We need to remove 36 to truncate the input but the first sequence has a length 33.
Iteration: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:01<00:00,  5.39it/s]
Epoch:  75%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                             | 3/4 [00:03<00:01,  1.21s/it]We need to remove 7 to truncate the input but the first sequence has a length 4.                                                                                                                         | 0/6 [00:00<?, ?it/s]
We need to remove 6 to truncate the input but the first sequence has a length 3.
We need to remove 9 to truncate the input but the first sequence has a length 6.
We need to remove 9 to truncate the input but the first sequence has a length 6.
We need to remove 13 to truncate the input but the first sequence has a length 10.
We need to remove 12 to truncate the input but the first sequence has a length 9.
We need to remove 14 to truncate the input but the first sequence has a length 11.
We need to remove 11 to truncate the input but the first sequence has a length 8.
                                                                                                                                                                                                                               We need to remove 11 to truncate the input but the first sequence has a length 8.                                                                                                                | 1/6 [00:00<00:00,  5.07it/s]
We need to remove 13 to truncate the input but the first sequence has a length 10.
We need to remove 11 to truncate the input but the first sequence has a length 8.
We need to remove 12 to truncate the input but the first sequence has a length 9.
We need to remove 10 to truncate the input but the first sequence has a length 7.
We need to remove 17 to truncate the input but the first sequence has a length 14.
We need to remove 14 to truncate the input but the first sequence has a length 11.
We need to remove 23 to truncate the input but the first sequence has a length 20.
                                                                                                                                                                                                                               We need to remove 14 to truncate the input but the first sequence has a length 11.                                                                                                               | 2/6 [00:00<00:00,  4.99it/s]
We need to remove 13 to truncate the input but the first sequence has a length 10.
We need to remove 10 to truncate the input but the first sequence has a length 7.
We need to remove 10 to truncate the input but the first sequence has a length 7.
We need to remove 36 to truncate the input but the first sequence has a length 33.
We need to remove 13 to truncate the input but the first sequence has a length 10.
We need to remove 16 to truncate the input but the first sequence has a length 13.
We need to remove 11 to truncate the input but the first sequence has a length 8.
                                                                                                                                                                                                                               We need to remove 6 to truncate the input but the first sequence has a length 3. ███████████████████████▌                                                                                        | 3/6 [00:00<00:00,  4.83it/s]
We need to remove 6 to truncate the input but the first sequence has a length 3.
We need to remove 13 to truncate the input but the first sequence has a length 10.
We need to remove 6 to truncate the input but the first sequence has a length 3.
We need to remove 15 to truncate the input but the first sequence has a length 12.
We need to remove 11 to truncate the input but the first sequence has a length 8.
We need to remove 11 to truncate the input but the first sequence has a length 8.
We need to remove 14 to truncate the input but the first sequence has a length 11.
                                                                                                                                                                                                                               We need to remove 14 to truncate the input but the first sequence has a length 11. ███████████████████████████████████████████████████                                                           | 4/6 [00:00<00:00,  4.91it/s]
We need to remove 11 to truncate the input but the first sequence has a length 8.
We need to remove 12 to truncate the input but the first sequence has a length 9.
We need to remove 12 to truncate the input but the first sequence has a length 9.
We need to remove 10 to truncate the input but the first sequence has a length 7.
We need to remove 13 to truncate the input but the first sequence has a length 10.
We need to remove 11 to truncate the input but the first sequence has a length 8.
We need to remove 10 to truncate the input but the first sequence has a length 7.
                                                                                                                                                                                                                               We need to remove 6 to truncate the input but the first sequence has a length 3. ██████████████████████████████████████████████████████████████████████████████████▌                             | 5/6 [00:01<00:00,  4.93it/s]
We need to remove 13 to truncate the input but the first sequence has a length 10.
We need to remove 14 to truncate the input but the first sequence has a length 11.
We need to remove 6 to truncate the input but the first sequence has a length 3.
We need to remove 42 to truncate the input but the first sequence has a length 39.
We need to remove 11 to truncate the input but the first sequence has a length 8.
We need to remove 18 to truncate the input but the first sequence has a length 15.
We need to remove 11 to truncate the input but the first sequence has a length 8.
Iteration: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:01<00:00,  5.00it/s]
Epoch: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:04<00:00,  1.23s/it]
wow! I think it may be caused by my sentence being too short, so should the word segmentation strategy be changed? I use the XLNET.
Here's my data format：
Total training samples: 24
[' The passenger thought he was using his balance on the app', 'The passenger thought she had put the payment option on her card and when she finished the ride it was in cash and she did not have any cash at the time.'] 1.0
[' Passenger thought he had put it on his card.', 'Passenger asked because the person who asked her said it was already paid online'] 1.0
['Passenger thought he still had a balance on the app', ' Customer said that this amount was passed on to her'] 1.0
['The passenger thought it was on the card', 'He informed that he had already paid'] 1.0
[' Passenger did not have the rest', 'You only paid 11 reais on pix'] 1.0

**Comment by ZHAOFEGNSHUN** [comment]
from torch.utils.data import DataLoader
import math
from sentence_transformers import SentenceTransformer, LoggingHandler, losses, models, util
from sentence_transformers.readers import InputExample
import logging
from datetime import datetime
import sys
import os
import gzip
import csv
from transformers import AutoTokenizer
from transformers import XLNetTokenizer


model_name = sys.argv[1] if len(sys.argv) > 1 else "/nfs/XLNet/XLNet/xlnet-base-cased"


# 读取数据集
train_batch_size = 16
num_epochs = 4
model_save_path = (
    "output/training_stsbenchmark_" + model_name.replace("/", "-") + "-" + datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
)

# 使用 Huggingface/transformers 模型 (例如 BERT, RoBERTa, XLNet, XLM-R) 将 tokens 映射到 embeddings
word_embedding_model = models.Transformer(model_name)
# 应用均值池化以获取固定大小的句子向量
pooling_model = models.Pooling(
    word_embedding_model.get_word_embedding_dimension(),
    pooling_mode_mean_tokens=True,
    pooling_mode_cls_token=False,
    pooling_mode_max_tokens=False,
)

model = SentenceTransformer(modules=[word_embedding_model, pooling_model])
model[0].tokenizer = XLNetTokenizer.from_pretrained(model_name, use_fast=False)


logging.info("读取训练数据集")
train_samples = []
# 打开CSV文件进行读取
with open('/nfs/XLNet/XLNet/乘客认为已支付.csv', "r", encoding="utf-8") as csvfile:
    reader = csv.DictReader(csvfile)
    # 遍历CSV文件中的每一行
    for row in reader:
        score = float(row["score"]) / 5.0  # 标准化分数到范围 0 ... 1
        sentence1 = row["sentence1"].replace(', ','<sep>') + '<sep>' + '<cls>'
        sentence2 = row["sentence2"].replace(', ','<sep>') + '<sep>' + '<cls>'
        # print('sentence1:',sentence1)
        # print('sentence2:',sentence2)
        inp_example = InputExample(texts=[sentence1, sentence2], label=score)
        train_samples.append(inp_example)

        # tokenize = model[0].tokenizer.tokenize(sentence1)
        # print('tokenized:', tokenize)

        # sample_texts = [sentence1, sentence2]
        # tokenized = model[0].tokenizer(sample_texts, padding=True, truncation=True, return_tensors="pt")
        # print('tokenized:', tokenized)
# print(f"Total training samples: {len(train_samples)}")
# for sample in train_samples[:5]:
#     print(sample.texts, sample.label)



train_dataloader = DataLoader(train_samples, shuffle=True, batch_size=4)
train_loss = losses.CosineSimilarityLoss(model=model)

# 设置 warm-up 步数
warmup_steps = math.ceil(len(train_dataloader) * num_epochs * 0.1)  # 10% 的训练数据用于 warm-up
print("Warmup-steps: {}".format(warmup_steps))
# logging.info("Warmup-steps: {}".format(warmup_steps))

# 开始训练
model.fit(
    train_objectives=[(train_dataloader, train_loss)],
    epochs=num_epochs,
    warmup_steps=warmup_steps,
    output_path=model_save_path,
)
This is my code.Is there something wrong with my code? 

Thank you very much for your reply！！！❤️
