### ISSUE TITLE
OSError: [WinError 126] The specified module could not be found -- cannot import SentenceTransformers

### ISSUE THREAD

**Issue by FanyiMo** [UKPLab/sentence-transformers#266]
**I installed sentence-transformers via this command:** 
pip install -U sentence-transformers

**and I tried to import SentenceTransformers via this:** 
from sentence_transformers import SentenceTransformer,, LoggingHandler

**I ran into this error:**
Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    from sentence_transformers import SentenceTransformer, LoggingHandler
  File "C:\Users\Fanyi Mo\AppData\Local\Programs\Python\Python37\lib\site-packages\sentence_transformers\__init__.py", line 3, in <module>
    from .datasets import SentencesDataset, SentenceLabelDataset, ParallelSentencesDataset
  File "C:\Users\Fanyi Mo\AppData\Local\Programs\Python\Python37\lib\site-packages\sentence_transformers\datasets\__init__.py", line 1, in <module>
    from .ParallelSentencesDataset import ParallelSentencesDataset
  File "C:\Users\Fanyi Mo\AppData\Local\Programs\Python\Python37\lib\site-packages\sentence_transformers\datasets\ParallelSentencesDataset.py", line 1, in <module>
    from torch.utils.data import Dataset
  File "C:\Users\Fanyi Mo\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\__init__.py", line 81, in <module>
    ctypes.CDLL(dll)
  File "C:\Users\Fanyi Mo\AppData\Local\Programs\Python\Python37\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found

Can anyone help?

**Comment by aqsa27** [comment]
Hi,
facing the same error while running the script containing Sentence Transformers on AWS Ec2 linux.

**Comment by nreimers** [comment]
It appears to be an error with pytorch, that it cannot be loaded / installed.

Try to install pytorch by hand following the installation description from torch.
