### ISSUE TITLE
cannot import name '_sentencepiece' from partially initialized module 'sentencepiece' (most likely due to a circular import) 

### ISSUE THREAD

**Issue by heiheiheibj** [UKPLab/sentence-transformers#2661]
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\langchain\ragtest.py", line 108, in <module>
    embeddings = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")
  File "D:\ProgramData\Anaconda3\envs\llm\lib\site-packages\langchain_community\embeddings\huggingface.py", line 64, in __init__
    import sentence_transformers
  File "D:\ProgramData\Anaconda3\envs\llm\lib\site-packages\sentence_transformers\__init__.py", line 3, in <module>
    from .datasets import SentencesDataset, ParallelSentencesDataset
  File "D:\ProgramData\Anaconda3\envs\llm\lib\site-packages\sentence_transformers\datasets\__init__.py", line 3, in <module>
    from .ParallelSentencesDataset import ParallelSentencesDataset
  File "D:\ProgramData\Anaconda3\envs\llm\lib\site-packages\sentence_transformers\datasets\ParallelSentencesDataset.py", line 4, in <module>
    from .. import SentenceTransformer
  File "D:\ProgramData\Anaconda3\envs\llm\lib\site-packages\sentence_transformers\SentenceTransformer.py", line 38, in <module>
    from .models import Transformer, Pooling, Normalize
  File "D:\ProgramData\Anaconda3\envs\llm\lib\site-packages\sentence_transformers\models\__init__.py", line 1, in <module>
    from .Transformer import Transformer
  File "D:\ProgramData\Anaconda3\envs\llm\lib\site-packages\sentence_transformers\models\Transformer.py", line 2, in <module>
    from transformers import AutoModel, AutoTokenizer, AutoConfig, T5Config, MT5Config
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "D:\ProgramData\Anaconda3\envs\llm\lib\site-packages\transformers\utils\import_utils.py", line 1525, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "D:\ProgramData\Anaconda3\envs\llm\lib\site-packages\transformers\utils\import_utils.py", line 1537, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.auto because of the following error (look up to see its traceback):
cannot import name '_sentencepiece' from partially initialized module 'sentencepiece' (most likely due to a circular import) (D:\ProgramData\Anaconda3\envs\llm\lib\site-packages\sentencepiece\__init__.py)

How to fix this problem?
thx.

**Comment by tomaarsen** [comment]
Hello!

This line in the traceback is a bit confusing to me:
```
File "", line 1075, in _handle_fromlist
```
That said, `sentencepiece` is no longer required by `transformers` or `sentence-transformers`. You might be able to just uninstall it to avoid the odd import issue:
```
pip uninstall sentencepiece
```

Let me know if that doesn't work.

- Tom Aarsen

**Comment by MeghaliBanerjee** [comment]
Aware this is an old thread but just posting since I ran into a similar error while trying to use the 'google/gemma-3-270m' model and searching my error message brought me to this post.

The suggested fix did not work for me, instead, I had to install sentencepiece. The model worked after that - I imagine a dependency was not loaded by default.

**Comment by tomaarsen** [comment]
Thanks for sharing your fix, if the model indeed requires `sentencepiece`, then attempting to (re-)install is a good option to try.

- Tom Aarsen
