### ISSUE TITLE
Fine Tune Clip no longer works in v3.0

### ISSUE THREAD

**Issue by Lucas-Garvey** [UKPLab/sentence-transformers#2691]
Keep getting this error, even when using a script that worked in the previous version. 

StopIteration: Caught StopIteration in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/torch/nn/parallel/parallel_apply.py", line 83, in _worker
    output = module(*input, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
            ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sentence_transformers/models/CLIPModel.py", line 46, in forward
    sentence_embedding.append(next(image_features))
                              ^^^^^^^^^^^^^^^^^^^^
StopIteration

**Comment by tomaarsen** [comment]
Hello!

Thanks for reporting, I'll look into this. In the meantime, you can use `old_fit` to get exactly the old behaviour. Apologies for the inconvenience.

- Tom Aarsen

**Comment by tomaarsen** [comment]
The CLIP training script: https://github.com/UKPLab/sentence-transformers/blob/fc1b7d0f308585e8caafbc9ca96af099b0931f73/examples/training/clip/train_clip.ipynb still seems to work. 

I'm curious in what extent your training setup differs from this one, as I'd like to get this fixed for better CLIP training support.

- Tom Aarsen

**Comment by sunzhaoyang1** [comment]
i have the same error
