### ISSUE TITLE
Add SentenceTransformer.encode(List[int]) method to accept encoded data as argument 

### ISSUE THREAD

**Issue by rjurney** [UKPLab/sentence-transformers#272]
It is problematic to put an encoding workload on a GPU that the `SentenceTransformer.encode(str)` API is the only way to apply the model. You can't easily get a list of strings into a GPU via PyTorch, but you can if you encode the data first and then create a Tensor from that data.

I propose to add the method `SentenceTransformer.encode(List[int])` or similar that accepts encoded data which will facilitate GPU encoding.

**Comment by rjurney** [comment]
This is in fact what needs to happen. I am creating an `embed(List[int])` method locally where I pre-encode the data using `transformers.BertTokenizer`.

Would this be accepted as a contribution? I have to scale tokenizing/encoding beforehand using Dask and then need to just apply the embedding using a GPU. The GPU can't take a `List[str]` so unless I'm wrong, this can't work on a GPU. If it is `List[int]` I can just use `tensor.from_numpy()` and then apply the model on big chunks of encoded sentences at once and it will scale.

**Comment by mokshasoft** [comment]
It seems like this should be available in the latest version considering the type hints on encode:
```
def encode(self, sentences: Union[str, List[str], List[int]],
```
but when running the below code I get an exception.
```
from sentence_transformers import SentenceTransformer

model = SentenceTransformer('KBLab/sentence-bert-swedish-cased')
sequence = "I've been waiting for a HuggingFace course my whole life."
tokenizer = AutoTokenizer.from_pretrained('KBLab/sentence-bert-swedish-cased')
ids = tokenizer(sequence)
emb = model.encode(ids.input_ids)
```

It tries to tokenize even though the input is a List of int.
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/bug.py", line 12, in <module>
    emb = model.encode(ids.input_ids)
  File "/venv/lib/python3.9/site-packages/sentence_transformers/SentenceTransformer.py", line 156, in encode
    features = self.tokenize(sentences_batch)
  File "/venv/lib/python3.9/site-packages/sentence_transformers/SentenceTransformer.py", line 309, in tokenize
    return self._first_module().tokenize(texts)
  File "/venv/lib/python3.9/site-packages/sentence_transformers/models/Transformer.py", line 88, in tokenize
    batch1.append(text_tuple[0])
TypeError: 'int' object is not subscriptable
```

Does anyone have an idea what is wrong?

**Comment by nreimers** [comment]
@mokshasoft The type hint is still from an old version, when it was supported. It was removed in the more recent versions and is no longer possible

**Comment by mokshasoft** [comment]
@nreimers Thanks, that's too bad it's no longer possible, but I copied it from the latest code on master. Maybe the type hint was forgotten during removal. I tried wrapping the ids in square brackets and then encode at least output something, but the cosine similarity between the two different ways of calling encode shows that it doesn't work.
```
emb1 = model.encode([ids.input_ids])[0]
emb2 = model.encode(sequence)
print(cosine_similarity(emb1, emb2))
0.07606422
```
