### ISSUE TITLE
RuntimeError: Placeholder storage has not been allocated on MPS device!

### ISSUE THREAD

**Issue by JakeRutherford** [UKPLab/sentence-transformers#2800]
I am running this basic training example on an Apple M3 Pro. I am using Python 3.10, sentence-transformers 3.0.1, accelerate 0.31 and torch 2.3.1.

```from sentence_transformers import SentenceTransformer, SentenceTransformerTrainer, losses
from datasets import Dataset

model = SentenceTransformer("all-MiniLM-L6-v2")
train_dataset = Dataset.from_dict({
    "anchor": ["It's nice weather outside today.", "He drove to work."],
    "positive": ["It's so sunny.", "He took the car to the office."],
    "negative": ["It's quite rainy, sadly.", "She walked to the store."],
})

loss = losses.TripletLoss(model=model)

trainer = SentenceTransformerTrainer(
    model=model,
    train_dataset=train_dataset,
    loss=loss,
)
trainer.train()```

I am getting this error:

```
poetry run python foo.py
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
  0%|                                                                                                                                                                                       | 0/3 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/Users/jakerutherford/Documents/vlexlabs-experiments/experiments/headnotes_embeddings/foo.py", line 18, in <module>
    trainer.train()
  File "/Users/jakerutherford/Library/Caches/pypoetry/virtualenvs/headnotes-embeddings-_XuWiqEr-py3.10/lib/python3.10/site-packages/transformers/trainer.py", line 1932, in train
    return inner_training_loop(
  File "/Users/jakerutherford/Library/Caches/pypoetry/virtualenvs/headnotes-embeddings-_XuWiqEr-py3.10/lib/python3.10/site-packages/transformers/trainer.py", line 2268, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/Users/jakerutherford/Library/Caches/pypoetry/virtualenvs/headnotes-embeddings-_XuWiqEr-py3.10/lib/python3.10/site-packages/transformers/trainer.py", line 3307, in training_step
    loss = self.compute_loss(model, inputs)
  File "/Users/jakerutherford/Library/Caches/pypoetry/virtualenvs/headnotes-embeddings-_XuWiqEr-py3.10/lib/python3.10/site-packages/sentence_transformers/trainer.py", line 329, in compute_loss
    loss = loss_fn(features, labels)
  File "/Users/jakerutherford/Library/Caches/pypoetry/virtualenvs/headnotes-embeddings-_XuWiqEr-py3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/jakerutherford/Library/Caches/pypoetry/virtualenvs/headnotes-embeddings-_XuWiqEr-py3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/jakerutherford/Library/Caches/pypoetry/virtualenvs/headnotes-embeddings-_XuWiqEr-py3.10/lib/python3.10/site-packages/sentence_transformers/losses/TripletLoss.py", line 79, in forward
    reps = [self.model(sentence_feature)["sentence_embedding"] for sentence_feature in sentence_features]
  File "/Users/jakerutherford/Library/Caches/pypoetry/virtualenvs/headnotes-embeddings-_XuWiqEr-py3.10/lib/python3.10/site-packages/sentence_transformers/losses/TripletLoss.py", line 79, in <listcomp>
    reps = [self.model(sentence_feature)["sentence_embedding"] for sentence_feature in sentence_features]
  File "/Users/jakerutherford/Library/Caches/pypoetry/virtualenvs/headnotes-embeddings-_XuWiqEr-py3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/jakerutherford/Library/Caches/pypoetry/virtualenvs/headnotes-embeddings-_XuWiqEr-py3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/jakerutherford/Library/Caches/pypoetry/virtualenvs/headnotes-embeddings-_XuWiqEr-py3.10/lib/python3.10/site-packages/torch/nn/modules/container.py", line 215, in forward
    input = module(input)
  File "/Users/jakerutherford/Library/Caches/pypoetry/virtualenvs/headnotes-embeddings-_XuWiqEr-py3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/jakerutherford/Library/Caches/pypoetry/virtualenvs/headnotes-embeddings-_XuWiqEr-py3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/jakerutherford/Library/Caches/pypoetry/virtualenvs/headnotes-embeddings-_XuWiqEr-py3.10/lib/python3.10/site-packages/sentence_transformers/models/Transformer.py", line 118, in forward
    output_states = self.auto_model(**trans_features, return_dict=False)
  File "/Users/jakerutherford/Library/Caches/pypoetry/virtualenvs/headnotes-embeddings-_XuWiqEr-py3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/jakerutherford/Library/Caches/pypoetry/virtualenvs/headnotes-embeddings-_XuWiqEr-py3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/jakerutherford/Library/Caches/pypoetry/virtualenvs/headnotes-embeddings-_XuWiqEr-py3.10/lib/python3.10/site-packages/transformers/models/bert/modeling_bert.py", line 1077, in forward
    embedding_output = self.embeddings(
  File "/Users/jakerutherford/Library/Caches/pypoetry/virtualenvs/headnotes-embeddings-_XuWiqEr-py3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/jakerutherford/Library/Caches/pypoetry/virtualenvs/headnotes-embeddings-_XuWiqEr-py3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/jakerutherford/Library/Caches/pypoetry/virtualenvs/headnotes-embeddings-_XuWiqEr-py3.10/lib/python3.10/site-packages/transformers/models/bert/modeling_bert.py", line 210, in forward
    inputs_embeds = self.word_embeddings(input_ids)
  File "/Users/jakerutherford/Library/Caches/pypoetry/virtualenvs/headnotes-embeddings-_XuWiqEr-py3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/jakerutherford/Library/Caches/pypoetry/virtualenvs/headnotes-embeddings-_XuWiqEr-py3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/jakerutherford/Library/Caches/pypoetry/virtualenvs/headnotes-embeddings-_XuWiqEr-py3.10/lib/python3.10/site-packages/torch/nn/modules/sparse.py", line 162, in forward
    return F.embedding(
  File "/Users/jakerutherford/Library/Caches/pypoetry/virtualenvs/headnotes-embeddings-_XuWiqEr-py3.10/lib/python3.10/site-packages/torch/nn/functional.py", line 2233, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Placeholder storage has not been allocated on MPS device!
```

How can this be resolved?

**Comment by tomaarsen** [comment]
Hello!

I don't think I've seen this issue before, but a bit more searching makes me suggest that perhaps you have to use `use_mps_device=True` in your `SentenceTransformerTrainingArguments`:

```python
from sentence_transformers import SentenceTransformer, SentenceTransformerTrainer, SentenceTransformerTrainingArguments, losses
from datasets import Dataset

model = SentenceTransformer("all-MiniLM-L6-v2")
train_dataset = Dataset.from_dict({
    "anchor": ["It's nice weather outside today.", "He drove to work."],
    "positive": ["It's so sunny.", "He took the car to the office."],
    "negative": ["It's quite rainy, sadly.", "She walked to the store."],
})

loss = losses.TripletLoss(model=model)

args = SentenceTransformerTrainingArguments(
    output_dir="test_trainer",
    use_mps_device=True,
)

trainer = SentenceTransformerTrainer(
    model=model,
    args=args,
    train_dataset=train_dataset,
    loss=loss,
)
trainer.train()
```

- Tom Aarsen

**Comment by JakeRutherford** [comment]
Hello @tomaarsen !

Unfortunately adding `use_mps_device=True` to the `SentenceTransformerTrainingArguments` still gives the same error 🤔: 

`RuntimeError: Placeholder storage has not been allocated on MPS device!`

**Comment by tomaarsen** [comment]
Hmm, could you print the `model.device` after it has been loaded? If it's not `"mps"`, could you move the model with `model.to("mps")`?
I'm able to find some threads online when searching for `RuntimeError: Placeholder storage has not been allocated on MPS device!`, but I'm not quite sure which might help. 

- Tom Aarsen

**Comment by wanggz** [comment]
Hi, I have the same error, and when I print the model.device after model loaded is "mps:0".

**Comment by scriptator** [comment]
I had a similar problem. In a testcase I wanted to train a small model, but neither initialising everything on MPS (`use_mps_device=True`, `model.to("mps")`) nor instructing it to use CPU (`use_cpu=True`, `model.to("cpu")`) worked. I always got the error message which the thread creator also gets.

I traced the problem why  back to the `Accelerator` from the accelerate library. The HuggingFace trainer calls `accelerator.prepare` on the model, which moves the model to MPS, even though we initially created it on CPU instructed the SentenceTransformer. The reason is the following code part in the `__init__` function of the accelerator state:
      
    env_device = os.environ.get("ACCELERATE_TORCH_DEVICE", None)
    self.device = torch.device(env_device) if env_device is not None else None

When setting the environment variable `ACCELERATE_TORCH_DEVICE` to `cpu` I can successfully train a (dummy) sentence transformer model on CPU. Disclaimer: I don't know yet whether this is actually a good approach.

**Comment by krzysztoflupa** [comment]
Just facing the same problem, setting up ACCELERATE_TORCH_DEVICE to cpu solves the problem temporarily as we all know how much faster is mps, Thanks @scriptator i will let you know if i find some solution.

**Comment by krzysztoflupa** [comment]
@scriptator It finally works on my M1, i havent used conda environment, to set it up just install miniconda (not by brew, by package) and follow instructions here and you'll be fine:

https://huggingface.co/docs/autotrain/quickstart

**Comment by mahaoyu** [comment]
Hi, just wanted to follow up on this - I think I'm still facing this issue.


I am experiencing the "RuntimeError: Placeholder storage has not been allocated on MPS device!" issue during training with `torch.nn.functional.embedding` while using the MPS backend on macOS. Here is a summary of my environment:

**Environment Details:**
- macOS Version: [your macOS version, e.g., 13.x]
- Python version: 3.12.x
- Apple Silicon: [M1/M2 chip details]
- Key Packages:
  - accelerate==1.0.1
  - datasets==3.1.0
  - numpy==1.26.4
  - torch==2.5.1
  - torchaudio==2.5.1
  - torchvision==0.20.1
  - transformers==4.42.4

**Description of the Issue:**
Despite following typical usage patterns with the Hugging Face `Trainer` API, I consistently encounter this error on MPS. Setting `ACCELERATE_TORCH_DEVICE=cpu` avoids the issue but defeats the purpose of MPS acceleration (as earlier shared by @scriptator).

Please let me know if further information or testing would be helpful.
