### ISSUE TITLE
`ModuleNotFoundError: No module named 'sentence_transformers.cross_encoder'`

### ISSUE THREAD

**Issue by harupy** [UKPLab/sentence-transformers#2822]
## How to reproduce the error

```
> pip install git+https://github.com/UKPLab/sentence-transformers
Collecting git+https://github.com/UKPLab/sentence-transformers
  Cloning https://github.com/UKPLab/sentence-transformers to /tmp/pip-req-build-hptg2s1o
  Running command git clone --filter=blob:none --quiet https://github.com/UKPLab/sentence-transformers /tmp/pip-req-build-hptg2s1o
  Resolved https://github.com/UKPLab/sentence-transformers to commit b56a987d644ae455ebdc3d2eccc9955348d2778e
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
...

> python -c 'import sentence_transformers'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/sentence_transformers/__init__.py", line 7, in <module>
    from sentence_transformers.cross_encoder.CrossEncoder import CrossEncoder
ModuleNotFoundError: No module named 'sentence_transformers.cross_encoder'
```

**Comment by harupy** [comment]
I think https://github.com/UKPLab/sentence-transformers/pull/2786 is the trigger.

**Comment by harupy** [comment]
`ls /usr/local/lib/python3.8/site-packages/sentence_transformers` output:

```
> ls /usr/local/lib/python3.8/site-packages/sentence_transformers
LoggingHandler.py       __pycache__       model_card.py            py.typed         similarity_functions.py  util.py
SentenceTransformer.py  data_collator.py  model_card_template.md   quantization.py  trainer.py
__init__.py             fit_mixin.py      model_card_templates.py  sampler.py       training_args.py
```

**Comment by tomaarsen** [comment]
Hello!

Thanks for reporting, that seems very plausible. @fpgmaas could you have a look at this perhaps? Otherwise I'll pick it up later this morning.

- Tom Aarsen

**Comment by fpgmaas** [comment]
I'll take a look now!

**Comment by tomaarsen** [comment]
Thanks a bunch for reporting this @harupy & for the fix @fpgmaas. The bleeding edge install should work again.

- Tom Aarsen
