### ISSUE TITLE
ImportError: cannot import name 'Dataset' from 'datasets' (unknown location)

### ISSUE THREAD

**Issue by nihilisticneuralnet** [UKPLab/sentence-transformers#2852]
```
Traceback (most recent call last):
  File "C:\Users\Acer\AppData\Roaming\Python\Python311\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 589, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\Acer\Pdf.py", line 3, in <module>
    from sentence_transformers import util
  File "C:\Users\Acer\AppData\Roaming\Python\Python311\site-packages\sentence_transformers\__init__.py", line 7, in <module>
    from sentence_transformers.cross_encoder.CrossEncoder import CrossEncoder
  File "C:\Users\Acer\AppData\Roaming\Python\Python311\site-packages\sentence_transformers\cross_encoder\__init__.py", line 1, in <module>
    from .CrossEncoder import CrossEncoder
  File "C:\Users\Acer\AppData\Roaming\Python\Python311\site-packages\sentence_transformers\cross_encoder\CrossEncoder.py", line 18, in <module>
    from sentence_transformers.SentenceTransformer import SentenceTransformer
  File "C:\Users\Acer\AppData\Roaming\Python\Python311\site-packages\sentence_transformers\SentenceTransformer.py", line 27, in <module>
    from sentence_transformers.model_card import SentenceTransformerModelCardData, generate_model_card
  File "C:\Users\Acer\AppData\Roaming\Python\Python311\site-packages\sentence_transformers\model_card.py", line 33, in <module>
    from datasets import Dataset, DatasetDict, Value
ImportError: cannot import name 'Dataset' from 'datasets' (unknown location)
```

**Comment by nihilisticneuralnet** [comment]
solve by using `pip install sentence-transformers[train]==3.0.1` instead of `pip install sentence-transformers==3.0.1`
