### ISSUE TITLE
Sentence Transformers / datasets dependency.

### ISSUE THREAD

**Issue by samrandall-blai** [UKPLab/sentence-transformers#2898]
If I have `datasets` as a locally available directory in my working directory and run `import sentence_transformers`, I get the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/Caskroom/miniforge/base/envs/test_embeddings_env/lib/python3.12/site-packages/sentence_transformers/__init__.py", line 7, in <module>
    from sentence_transformers.cross_encoder.CrossEncoder import CrossEncoder
  File "/opt/homebrew/Caskroom/miniforge/base/envs/test_embeddings_env/lib/python3.12/site-packages/sentence_transformers/cross_encoder/__init__.py", line 1, in <module>
    from .CrossEncoder import CrossEncoder
  File "/opt/homebrew/Caskroom/miniforge/base/envs/test_embeddings_env/lib/python3.12/site-packages/sentence_transformers/cross_encoder/CrossEncoder.py", line 18, in <module>
    from sentence_transformers.SentenceTransformer import SentenceTransformer
  File "/opt/homebrew/Caskroom/miniforge/base/envs/test_embeddings_env/lib/python3.12/site-packages/sentence_transformers/SentenceTransformer.py", line 27, in <module>
    from sentence_transformers.model_card import SentenceTransformerModelCardData, generate_model_card
  File "/opt/homebrew/Caskroom/miniforge/base/envs/test_embeddings_env/lib/python3.12/site-packages/sentence_transformers/model_card.py", line 33, in <module>
    from datasets import Dataset, DatasetDict, Value
ImportError: cannot import name 'Dataset' from 'datasets' (unknown location)```

**Comment by ir2718** [comment]
Hi,

this could be due to sentence transformers relying on the datasets library. Try changing the name of your directory to something else and see if that works.

**Comment by tomaarsen** [comment]
@ir2718 is indeed right. #2858 and #2817 are related issues, and #2859 was created to resolve it (by checking if the `datasets` that can be imported is indeed the [`datasets`](https://pypi.org/project/datasets/) published by Hugging Face).

- Tom Aarsen

**Comment by samrandall-blai** [comment]
Yes, #2859 is a a solution to this issue. Thanks!
