### ISSUE TITLE
Fine-tuning with StaticEmbedding and CachedMultipleNegativesRankingLoss not working

### ISSUE THREAD

**Issue by aoezdTchibo** [UKPLab/sentence-transformers#2982]
I am trying to fine-tune a base model for my specific downstream task which was distilled with Model2Vec. Unfortunately I am getting the following error when I use the CachedMultipleNegativesRankingLoss:

```
Traceback (most recent call last):
  File "/home/jupyter/st-ft/st_trainer.py", line 55, in <module>
    trainer.train()
  File "/home/jupyter/st-ft/.venv/lib/python3.10/site-packages/transformers/trainer.py", line 1938, in train
    return inner_training_loop(
  File "/home/jupyter/st-ft/.venv/lib/python3.10/site-packages/transformers/trainer.py", line 2279, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/jupyter/st-ft/.venv/lib/python3.10/site-packages/transformers/trainer.py", line 3318, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home/jupyter/st-ft/.venv/lib/python3.10/site-packages/sentence_transformers/trainer.py", line 344, in compute_loss
    loss = loss_fn(features, labels)
  File "/home/jupyter/st-ft/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/jupyter/st-ft/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jupyter/st-ft/.venv/lib/python3.10/site-packages/sentence_transformers/losses/CachedMultipleNegativesRankingLoss.py", line 267, in forward
    for reps_mb, random_state in self.embed_minibatch_iter(
  File "/home/jupyter/st-ft/.venv/lib/python3.10/site-packages/sentence_transformers/losses/CachedMultipleNegativesRankingLoss.py", line 185, in embed_minibatch_iter
    bsz, _ = input_ids.shape
ValueError: not enough values to unpack (expected 2, got 1)
```

Here is an example training snippet for replicating the error:

```python
from datasets import load_dataset
from sentence_transformers import (
    SentenceTransformer,
    SentenceTransformerTrainer,
    SentenceTransformerTrainingArguments,
    SentenceTransformerModelCardData,
)
from sentence_transformers.losses import MultipleNegativesRankingLoss
from sentence_transformers.training_args import BatchSamplers
from sentence_transformers.evaluation import TripletEvaluator
from sentence_transformers.models import StaticEmbedding

# Initialize a Sentence Transformer model with a static embedding from a pretrained model2vec model
static_embedding = StaticEmbedding.from_distillation(
    "intfloat/multilingual-e5-small",
    device="cuda",
    pca_dims=256,
    apply_zipf=True,
)
model = SentenceTransformer(modules=[static_embedding])

# 3. Load a dataset to finetune on
dataset = load_dataset("sentence-transformers/all-nli", "triplet")
train_dataset = dataset["train"].select(range(100_000))
eval_dataset = dataset["dev"]
test_dataset = dataset["test"]

# 4. Define a loss function
loss = MultipleNegativesRankingLoss(model)

# 5. (Optional) Specify training arguments
batch_size = 2 ** 12
args = SentenceTransformerTrainingArguments(
    # Required parameter:
    output_dir="models/multilingual-e5-small-distilled",
    num_train_epochs=1,
    per_device_train_batch_size=batch_size,
    per_device_eval_batch_size=batch_size,
    batch_sampler=BatchSamplers.NO_DUPLICATES,
    eval_strategy="steps",
    eval_steps=5,
)

# 6. (Optional) Create an evaluator & evaluate the base model
dev_evaluator = TripletEvaluator(
    anchors=eval_dataset["anchor"],
    positives=eval_dataset["positive"],
    negatives=eval_dataset["negative"],
    name="all-nli-dev",
)
dev_evaluator(model)

# 7. Create a trainer & train
trainer = SentenceTransformerTrainer(
    model=model,
    args=args,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset,
    loss=loss,
    evaluator=dev_evaluator,
)
trainer.train()
```

**Comment by tomaarsen** [comment]
Hello!

I'll dive into this some more soon. In the meantime, consider using `MultipleNegativesRankingLoss`, perhaps that one does work as expected.

- Tom Aarsen

**Comment by aoezdTchibo** [comment]
Hi!

Fine-tuning with `MultipleNegativesRankingLoss` works, even with bigger batch sizes. So practically I was able to reproduce my previous training setup. Thanks!

**Comment by aoezdTchibo** [comment]
I have adapted the training script a little and started fine-tuning. Firstly, it is immensely fast. But I noticed a few things. The following evaluation losses came to light:

* 2.8591532707214355 (Epoch 0.2)
* 2.858781099319458 (Epoch 0.4)
* 2.8585245609283447 (Epoch 0.6)
* 2.8583667278289795 (Epoch 0.8)
* 2.8583083152770996 (Epoch 1.0)

It seems to me that fine-tuning has no effect, as the evaluation loss does not improve in any way, right?

Finally, for my specific task, the evaluation loss had been remarkably high and throughout training did not change either. Afterwards, it quickly became clear that my distilled fine-tuned model was fast but unusable.

**Comment by tomaarsen** [comment]
@aoezdTchibo Something that I forgot until just now is that in my experiments with training the StaticEmbedding-based Sentence Transformer, is that you have to use considerably higher learning rates than normal. 

Default learning rate: 5e-5
```python
{'loss': 5.8561, 'learning_rate': 4e-05, 'epoch': 0.2}
{'eval_loss': 2.8591532707214355, 'eval_all-nli-dev_cosine_accuracy': 0.7648845686512759, 'epoch': 0.2}
{'loss': 5.9103, 'learning_rate': 3e-05, 'epoch': 0.4}                                                                                                          
{'eval_loss': 2.8587820529937744, 'eval_all-nli-dev_cosine_accuracy': 0.7645808019441069, 'epoch': 0.4}
{'loss': 5.7194, 'learning_rate': 2e-05, 'epoch': 0.6}                                                                                                          
{'eval_loss': 2.8585257530212402, 'eval_all-nli-dev_cosine_accuracy': 0.7645808019441069, 'epoch': 0.6}
{'loss': 5.6334, 'learning_rate': 1e-05, 'epoch': 0.8}                                                                                                          
{'eval_loss': 2.858367443084717, 'eval_all-nli-dev_cosine_accuracy': 0.7645808019441069, 'epoch': 0.8}
{'loss': 5.4788, 'learning_rate': 0.0, 'epoch': 1.0}                                                                                                           
{'eval_loss': 2.8583085536956787, 'eval_all-nli-dev_cosine_accuracy': 0.7647326852976913, 'epoch': 1.0}
```

Much higher learning rate: 2e-1
```python
{'loss': 4.8993, 'learning_rate': 0.16000000000000003, 'epoch': 0.2}
{'eval_loss': 2.1595685482025146, 'eval_all-nli-dev_cosine_accuracy': 0.8133353584447145, 'epoch': 0.2}
{'loss': 3.6973, 'learning_rate': 0.12, 'epoch': 0.4}                                                                                                          
{'eval_loss': 2.077965259552002, 'eval_all-nli-dev_cosine_accuracy': 0.8251822600243013, 'epoch': 0.4}
{'loss': 3.192, 'learning_rate': 0.08000000000000002, 'epoch': 0.6}                                                                                            
{'eval_loss': 2.0159897804260254, 'eval_all-nli-dev_cosine_accuracy': 0.8306500607533415, 'epoch': 0.6}
{'loss': 3.0303, 'learning_rate': 0.04000000000000001, 'epoch': 0.8}                                                                                           
{'eval_loss': 2.0030393600463867, 'eval_all-nli-dev_cosine_accuracy': 0.8330801944106926, 'epoch': 0.8}
{'loss': 2.9063, 'learning_rate': 0.0, 'epoch': 1.0}                                                                                                           
{'eval_loss': 2.003547191619873, 'eval_all-nli-dev_cosine_accuracy': 0.8336877278250304, 'epoch': 1.0}
```

I think that should help a lot - it did for me when I trained https://huggingface.co/tomaarsen/static-bert-uncased-gooaq

---

As for the Cached... loss - that one is indeed incompatible as it expects the `input_ids` to be different. I'll add errors for those.

- Tom Aarsen

**Comment by aoezdTchibo** [comment]
@tomaarsen It indeed did help A LOT! My custom distilled model now provides useable embeddings which are suitable for our custom semantic product search. On my local machine I was able to drop the retrieval time from ca. 1 second down to ca. 35ms. That is insane! 🤯
I mean, sure, the distilled fine-tuned model is not always optimal but still produces good results!

Thank you very much. Really grateful! Amazing work!
