### ISSUE TITLE
Error while generating model card: model_card.py#line=435), in set_widget_examples indices, _ = zip(*sorted(lengths.items(), key=lambda x: x[1])) ValueError: not enough values to unpack (expected 2, got 0)

### ISSUE THREAD

**Issue by yaohwang** [UKPLab/sentence-transformers#2996]
Get this error while train SentenceTransformerTrainer under Jupyter Lab

```
Error while generating model card:
Traceback (most recent call last):
  File "[/usr/local/lib/python3.10/dist-packages/sentence_transformers/SentenceTransformer.py", line 1253](http://*****/usr/local/lib/python3.10/dist-packages/sentence_transformers/SentenceTransformer.py#line=1252), in _create_model_card
    model_card = generate_model_card(self)
  File "[/usr/local/lib/python3.10/dist-packages/sentence_transformers/model_card.py", line 973](http://*****/usr/local/lib/python3.10/dist-packages/sentence_transformers/model_card.py#line=972), in generate_model_card
    model_card = ModelCard.from_template(card_data=model.model_card_data, template_path=template_path, hf_emoji="🤗")
  File "[/usr/local/lib/python3.10/dist-packages/huggingface_hub/repocard.py", line 415](http://*****/usr/local/lib/python3.10/dist-packages/huggingface_hub/repocard.py#line=414), in from_template
    return super().from_template(card_data, template_path, template_str, **template_kwargs)
  File "[/usr/local/lib/python3.10/dist-packages/huggingface_hub/repocard.py", line 325](http://*****/usr/local/lib/python3.10/dist-packages/huggingface_hub/repocard.py#line=324), in from_template
    kwargs = card_data.to_dict().copy()
  File "[/usr/local/lib/python3.10/dist-packages/sentence_transformers/model_card.py", line 900](http://*****/usr/local/lib/python3.10/dist-packages/sentence_transformers/model_card.py#line=899), in to_dict
    self.set_widget_examples(dataset)
  File "[/usr/local/lib/python3.10/dist-packages/sentence_transformers/model_card.py", line 436](http://*****/usr/local/lib/python3.10/dist-packages/sentence_transformers/model_card.py#line=435), in set_widget_examples
    indices, _ = zip(*sorted(lengths.items(), key=lambda x: x[1]))
ValueError: not enough values to unpack (expected 2, got 0)
Consider opening an issue on https://github.com/UKPLab/sentence-transformers/issues with this traceback.
Skipping model card creation.
```

**Comment by yaohwang** [comment]
Hi @tomaarsen, good for that, but When I dig deep on my case, I think it's better to support feature.dtype == "large_string", not just feature.dtype == "string". if that's ok I will make a PR for that.

**Comment by tomaarsen** [comment]
Oh, that's excellent! I didn't realise that "large_string" existed, but I see it now in the [datasets docs](https://huggingface.co/docs/datasets/v3.0.1/en/package_reference/main_classes#datasets.Value). I would certainly welcome a PR.

- Tom Aarsen
