### ISSUE TITLE
backend="onnx" IndexError: tuple index out of range

### ISSUE THREAD

**Issue by loretoparisi** [UKPLab/sentence-transformers#3004]
I'm getting a `IndexError: tuple index out of range` when using new `backend` option `onnx` with model `distiluse-base-multilingual-cased`.
Interestingly I get a warning
```
Multiple ONNX files found in 'sentence-transformers/distiluse-base-multilingual-cased': ['onnx/model.onnx', 

'onnx/model_O1.onnx', 'onnx/model_O2.onnx', 'onnx/model_O3.onnx', 'onnx/model_O4.onnx', 'onnx/model_qint8_arm64.onnx', 

'onnx/model_qint8_avx512.onnx', 'onnx/model_qint8_avx512_vnni.onnx', 'onnx/model_quint8_avx2.onnx'], defaulting to 'onnx/model.onnx'. 
Please specify the desired file name via `model_kwargs={"file_name": "<file_name>"}`.
```

## Stacktrace
```
    embeddings = model.encode (sentences)
  File "/opt/conda/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py", line 621, in encode
    out_features = self.forward(features, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py", line 688, in forward
    input = module(input, **module_kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/sentence_transformers/models/Transformer.py", line 360, in forward
    hidden_states = output_states[all_layer_idx]
  File "/opt/conda/lib/python3.10/site-packages/transformers/utils/generic.py", line 433, in __getitem__
    return self.to_tuple()[k]
IndexError: tuple index out of range
```
## How To Reproduce
```python
from sentence_transformers import SentenceTransformer

model_name="distiluse-base-multilingual-cased"
model = SentenceTransformer (model_name, backend="onnx")
print(model)

sentences = ["This is an example sentence", "Each sentence is converted" ]
embeddings = model.encode (sentences)
print(embeddings)

```

**Comment by loretoparisi** [comment]
This issue could be related to https://github.com/UKPLab/sentence-transformers/issues/2983

**Comment by loretoparisi** [comment]
**[UPDATE]**

I was able to correctly convert at run time
- intfloat/multilingual-e5-large-instruct
- intfloat/multilingual-e5-base

while for `intfloat/multilingual-e5-small` I get the error `'NoneType' object has no attribute 'numpy'`.

## How To Reproduce
```python
# sentence-transformers-3.2.0 tokenizers-0.20.1 transformers-4.45.2
# pip install optimum[onnxruntime]` or `pip install optimum[onnxruntime-gpu]
from sentence_transformers import SentenceTransformer

import torch
import torch.nn.functional as F
from torch import Tensor

from optimum.onnxruntime import ORTModelForFeatureExtraction
from transformers import AutoTokenizer

def average_pool(last_hidden_states: Tensor,
                 attention_mask: Tensor) -> Tensor:
    last_hidden = last_hidden_states.masked_fill(~attention_mask[..., None].bool(), 0.0)
    return last_hidden.sum(dim=1) / attention_mask.sum(dim=1)[..., None]

device = "cpu" if torch.cuda.is_available() is False else "cuda"
cache_folder='./sbert'

# top 10 MTEB leaderboard multilingual embeddings models
models = [
    { 'name': 'distilbert/distilbert-base-multilingual-cased', 'dim': 768 },
    {'name':'intfloat/multilingual-e5-large-instruct', 'dim':768},
    {'name':'intfloat/multilingual-e5-base', 'dim':768},
    {'name':'intfloat/multilingual-e5-small', 'dim':384}
]

for model in models:
    try:
        
        model_name = model['name']
        model_dim = model['dim']
        print(f"[INFO] Loading model name:{model_name} dim:{model_dim}")
        
        tokenizer = AutoTokenizer.from_pretrained(f"{model_name}-onnx")
        model = ORTModelForFeatureExtraction.from_pretrained(f"{model_name}-onnx", 
                                                             cache_dir=cache_folder, 
                                                             provider="CPUExecutionProvider")
        print(model)
        
        sentences = ["This is an example sentence", "Each sentence is converted" ]
        encoded = tokenizer(sentences, max_length=512, padding=True, truncation=True, return_tensors='pt').to(device)

        with torch.no_grad():
            outputs = model(**encoded)
            #embeddings = outputs.last_hidden_state[:, 0][:model_dim]
            embeddings = average_pool(outputs.last_hidden_state, encoded['attention_mask'])
            embeddings = F.normalize(embeddings, p=2, dim=1) # normalize embeddings
            print( embeddings )
        
    except Exception as e:
        print(f"[WARN] errror with {model_name} {str(e)}")
        print(f"[INFO] Converting model name:{model_name} dim:{model_dim}")
        model = ORTModelForFeatureExtraction.from_pretrained(model_name, 
                                                             cache_dir=cache_folder, 
                                                             export=True)
        tokenizer = AutoTokenizer.from_pretrained(model_name)
        model.save_pretrained(f"{model_name}-onnx", cache_dir=cache_folder)
        tokenizer.save_pretrained(f"{model_name}-onnx", cache_dir=cache_folder)
        print(model)
```

the output was
```bash
[INFO] Loading model name:distilbert/distilbert-base-multilingual-cased dim:768
<optimum.onnxruntime.modeling_ort.ORTModelForFeatureExtraction object at 0x7f2fcb336740>
tensor([[ 0.0173, -0.0299,  0.0193,  ...,  0.0367,  0.0170, -0.0021],
        [ 0.0301, -0.0387,  0.0029,  ...,  0.0646,  0.0176, -0.0215]])
[INFO] Loading model name:intfloat/multilingual-e5-large-instruct dim:768
<optimum.onnxruntime.modeling_ort.ORTModelForFeatureExtraction object at 0x7f2fcb2f5c60>
tensor([[ 0.0395,  0.0044, -0.0024,  ..., -0.0278, -0.0361,  0.0136],
        [ 0.0387,  0.0115,  0.0030,  ..., -0.0253, -0.0432,  0.0418]])
[INFO] Loading model name:intfloat/multilingual-e5-base dim:768
<optimum.onnxruntime.modeling_ort.ORTModelForFeatureExtraction object at 0x7f2fcb2f4f40>
tensor([[ 0.0055,  0.0272, -0.0169,  ..., -0.0466, -0.0315,  0.0528],
        [ 0.0368,  0.0429, -0.0210,  ..., -0.0285, -0.0219,  0.0414]])
[INFO] Loading model name:intfloat/multilingual-e5-small dim:384
<optimum.onnxruntime.modeling_ort.ORTModelForFeatureExtraction object at 0x7f2fcb2d3ee0>
[WARN] errror with intfloat/multilingual-e5-small 'NoneType' object has no attribute 'numpy'
[INFO] Converting model name:intfloat/multilingual-e5-small dim:384
<optimum.onnxruntime.modeling_ort.ORTModelForFeatureExtraction object at 0x7f2fb19058d0>
```

adding the `traceback` the error comes out

```bash
    outputs = model(**encoded)
  File "/opt/conda/lib/python3.10/site-packages/optimum/modeling_base.py", line 98, in __call__
    return self.forward(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/optimum/onnxruntime/modeling_ort.py", line 1106, in forward
    onnx_inputs = self._prepare_onnx_inputs(use_torch, **model_inputs)
  File "/opt/conda/lib/python3.10/site-packages/optimum/onnxruntime/modeling_ort.py", line 940, in _prepare_onnx_inputs
    onnx_inputs[input_name] = onnx_inputs[input_name].numpy(force=True)
AttributeError: 'NoneType' object has no attribute 'numpy'
```

**Comment by tomaarsen** [comment]
Hello! 

Thanks for reporting this, and also providing more info in #2983. 

The `intfloat/multilingual-e5-small` issue I believe is related to https://github.com/huggingface/optimum/issues/2062, so that should be fixed soon enough.

The other issues, i.e. `IndexError: tuple index out of range`, is due to this: https://github.com/UKPLab/sentence-transformers/blob/29535eb44d270f5665e389aeb7e18cf04cb51bf0/sentence_transformers/models/Transformer.py#L355-L361

The config specifies that the model outputs the hidden states, but the ONNX model doesn't uphold this. This is something that I should fix on my side, thanks for reporting this! I'll make a PR in a few minutes.

- Tom Aarsen

**Comment by loretoparisi** [comment]
@tomaarsen using `sentence-transformers>=3.2.1` I try `sentence-transformers/all-MiniLM-L6-v2` it breaks again with the old error:

```python
# Tokenize sentences
            encoded_input = self.tokenizer(input_list, 
                                           padding=True, 
                                           truncation=True, 
                                           max_length=512,
                                           return_tensors='pt').to(device)
            # model forward pass
            if self.model_name=='sentence-transformers/all-MiniLM-L6-v2':
                # Compute token embeddings
                with torch.no_grad():
                    model_output = self.model(**encoded_input).to(device)
                    print(model_output)
                    # Perform pooling. In this case, cls pooling.
                    sentence_embeddings = model_output[0][:, 0]
                # ndarray to pytorch array
                sentence_embeddings = torch.tensor(sentence_embeddings)
                # Normalize embeddings
                sentence_embeddings = torch.nn.functional.normalize(sentence_embeddings, p=2, dim=1)
            else:
                # Compute token embeddings
                with torch.no_grad():
                    model_output = self.model(**encoded_input)
                sentence_embeddings = average_pool(model_output.last_hidden_state, encoded_input['attention_mask'])
                sentence_embeddings = F.normalize(sentence_embeddings, p=2, dim=1)
```

I get

```
2024-10-24 17:49:34 ONNXEmbeddingService loaded model:sentence-transformers/all-MiniLM-L6-v2 provider:CUDAExecutionProvider on device:cuda:0
2024-10-24 17:49:35 list index out of range
Traceback (most recent call last):
    model_output = self.model(**encoded_input).to(device)
  File "/home/coder/.local/lib/python3.10/site-packages/optimum/modeling_base.py", line 98, in __call__
    return self.forward(*args, **kwargs)
  File "/home/coder/.local/lib/python3.10/site-packages/optimum/onnxruntime/modeling_ort.py", line 1090, in forward
    io_binding, output_shapes, output_buffers = self.prepare_io_binding(
  File "/home/coder/.local/lib/python3.10/site-packages/optimum/onnxruntime/modeling_ort.py", line 908, in prepare_io_binding
    return self._prepare_io_binding(
  File "/home/coder/.local/lib/python3.10/site-packages/optimum/onnxruntime/modeling_ort.py", line 844, in _prepare_io_binding
    name = ordered_input_names[idx]
IndexError: list index out of range
```

while `'sentence-transformers/distiluse-base-multilingual-cased'` or `'intfloat/multilingual-e5-base'` works!
