### ISSUE TITLE
import sentence_transformers出错

### ISSUE THREAD

**Issue by qsuzer** [UKPLab/sentence-transformers#3135]
为什么我import以下模块会报错呢：
from sentence_transformers import SentenceTransformer
报这样的错：
Traceback (most recent call last):
  File "/home/wmz/FlashRAG/try2.py", line 1, in <module>
    from sentence_transformers import SentenceTransformer
  File "/data/anaconda3/envs/flashrag/lib/python3.9/site-packages/sentence_transformers/__init__.py", line 10, in <module>
    from sentence_transformers.cross_encoder.CrossEncoder import CrossEncoder
  File "/data/anaconda3/envs/flashrag/lib/python3.9/site-packages/sentence_transformers/cross_encoder/__init__.py", line 3, in <module>
    from .CrossEncoder import CrossEncoder
  File "/data/anaconda3/envs/flashrag/lib/python3.9/site-packages/sentence_transformers/cross_encoder/CrossEncoder.py", line 18, in <module>
    from sentence_transformers.evaluation.SentenceEvaluator import SentenceEvaluator
  File "/data/anaconda3/envs/flashrag/lib/python3.9/site-packages/sentence_transformers/evaluation/__init__.py", line 3, in <module>
    from .BinaryClassificationEvaluator import BinaryClassificationEvaluator
  File "/data/anaconda3/envs/flashrag/lib/python3.9/site-packages/sentence_transformers/evaluation/BinaryClassificationEvaluator.py", line 10, in <module>
    from sklearn.metrics import average_precision_score
  File "/data/anaconda3/envs/flashrag/lib/python3.9/site-packages/sklearn/__init__.py", line 73, in <module>
    from .base import clone  # noqa: E402
  File "/data/anaconda3/envs/flashrag/lib/python3.9/site-packages/sklearn/base.py", line 19, in <module>
    from .utils._estimator_html_repr import _HTMLDocumentationLinkMixin, estimator_html_repr
  File "/data/anaconda3/envs/flashrag/lib/python3.9/site-packages/sklearn/utils/__init__.py", line 15, in <module>
    from ._chunking import gen_batches, gen_even_slices
  File "/data/anaconda3/envs/flashrag/lib/python3.9/site-packages/sklearn/utils/_chunking.py", line 11, in <module>
    from ._param_validation import Interval, validate_params
  File "/data/anaconda3/envs/flashrag/lib/python3.9/site-packages/sklearn/utils/_param_validation.py", line 17, in <module>
    from .validation import _is_arraylike_not_scalar
  File "/data/anaconda3/envs/flashrag/lib/python3.9/site-packages/sklearn/utils/validation.py", line 21, in <module>
    from ..utils._array_api import _asarray_with_order, _is_numpy_namespace, get_namespace
  File "/data/anaconda3/envs/flashrag/lib/python3.9/site-packages/sklearn/utils/_array_api.py", line 17, in <module>
    from .fixes import parse_version
  File "/data/anaconda3/envs/flashrag/lib/python3.9/site-packages/sklearn/utils/fixes.py", line 17, in <module>
    import scipy.stats
  File "/data/anaconda3/envs/flashrag/lib/python3.9/site-packages/scipy/stats/__init__.py", line 606, in <module>
    from ._stats_py import *
  File "/data/anaconda3/envs/flashrag/lib/python3.9/site-packages/scipy/stats/_stats_py.py", line 49, in <module>
    from . import distributions
  File "/data/anaconda3/envs/flashrag/lib/python3.9/site-packages/scipy/stats/distributions.py", line 11, in <module>
    from . import _discrete_distns
  File "/data/anaconda3/envs/flashrag/lib/python3.9/site-packages/scipy/stats/_discrete_distns.py", line 10, in <module>
    from scipy.interpolate import interp1d
  File "/data/anaconda3/envs/flashrag/lib/python3.9/site-packages/scipy/interpolate/__init__.py", line 167, in <module>
    from ._interpolate import *
  File "/data/anaconda3/envs/flashrag/lib/python3.9/site-packages/scipy/interpolate/_interpolate.py", line 14, in <module>
    from . import _fitpack_py
  File "/data/anaconda3/envs/flashrag/lib/python3.9/site-packages/scipy/interpolate/_fitpack_py.py", line 8, in <module>
    from ._fitpack_impl import bisplrep, bisplev, dblint  # noqa: F401
  File "/data/anaconda3/envs/flashrag/lib/python3.9/site-packages/scipy/interpolate/_fitpack_impl.py", line 103, in <module>
    'iwrk': array([], dfitpack_int), 'u': array([], float),
TypeError

sentence-transformers的版本是3.2.1

**Comment by tomaarsen** [comment]
Hello!

Other people have this issue too I think: https://github.com/scipy/scipy/issues/21014
Some people offered solutions:
* Increase Python version
* `pip install scipy==1.14.1` or `pip install 'scipy<1.13.0'`
* reinstall scipy

Consider trying out a few options there.

- Tom Aarsen
