### ISSUE TITLE
fine-tune error RuntimeError: expected dtype Float but got dtype Long 

### ISSUE THREAD

**Issue by MrRace** [UKPLab/sentence-transformers#322]
When fine-tune on my own data, error happen when run `model.fit`
```
Traceback (most recent call last):
  File "fine_tune_sbert.py", line 109, in <module>
    output_path=model_save_path)
  File "/opt/conda/lib/python3.7/site-packages/sentence_transformers/SentenceTransformer.py", line 402, in fit
    loss_value.backward()
  File "/opt/conda/lib/python3.7/site-packages/torch/tensor.py", line 198, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/opt/conda/lib/python3.7/site-packages/torch/autograd/__init__.py", line 100, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: expected dtype Float but got dtype Long (validate_dtype at /pytorch/aten/src/ATen/native/TensorIterator.cpp:143)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x46 (0x7f4a9deda536 in /opt/conda/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: at::TensorIterator::compute_types() + 0xce3 (0x7f4adb981a23 in /opt/conda/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #2: at::TensorIterator::build() + 0x44 (0x7f4adb984404 in /opt/conda/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #3: at::native::mse_loss_backward_out(at::Tensor&, at::Tensor const&, at::Tensor const&, at::Tensor const&, long) + 0x193 (0x7f4adb7d1953 in /opt/conda/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #4: <unknown function> + 0xf903d7 (0x7f4a9f2c63d7 in /opt/conda/lib/python3.7/site-packages/torch/lib/libtorch_cuda.so)
frame #5: at::native::mse_loss_backward(at::Tensor const&, at::Tensor const&, at::Tensor const&, long) + 0x172 (0x7f4adb7da092 in /opt/conda/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #6: <unknown function> + 0xf9068f (0x7f4a9f2c668f in /opt/conda/lib/python3.7/site-packages/torch/lib/libtorch_cuda.so)
frame #7: <unknown function> + 0x10c2536 (0x7f4adbc0a536 in /opt/conda/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #8: <unknown function> + 0x2a9ecdb (0x7f4add5e6cdb in /opt/conda/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #9: <unknown function> + 0x10c2536 (0x7f4adbc0a536 in /opt/conda/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #10: torch::autograd::generated::MseLossBackward::apply(std::vector<at::Tensor, std::allocator<at::Tensor> >&&) + 0x1f7 (0x7f4add3ee777 in /opt/conda/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #11: <unknown function> + 0x2d89705 (0x7f4add8d1705 in /opt/conda/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #12: torch::autograd::Engine::evaluate_function(std::shared_ptr<torch::autograd::GraphTask>&, torch::autograd::Node*, torch::autograd::InputBuffer&) + 0x16f3 (0x7f4add8cea03 in /opt/conda/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #13: torch::autograd::Engine::thread_main(std::shared_ptr<torch::autograd::GraphTask> const&, bool) + 0x3d2 (0x7f4add8cf7e2 in /opt/conda/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #14: torch::autograd::Engine::thread_init(int) + 0x39 (0x7f4add8c7e59 in /opt/conda/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #15: torch::autograd::python::PythonEngine::thread_init(int) + 0x38 (0x7f4aea20fac8 in /opt/conda/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #16: <unknown function> + 0xbd66f (0x7f4aeb0bf66f in /usr/lib/x86_64-linux-gnu/libstdc++.so.6)
frame #17: <unknown function> + 0x76db (0x7f4aece476db in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #18: clone + 0x3f (0x7f4aecb7088f in /lib/x86_64-linux-gnu/libc.so.6)
```
My torch version is `1.15`

**Comment by MrRace** [comment]
After setting the label value `float` type, it can work now. But Why? The label value should be `string` type, as the labels in raw data are "1"(similar) and "0"(dissimilar).

**Comment by nreimers** [comment]
Hi @MrRace 
In general I can recommend to update to the latest pytorch version, as it is much faster than the old 1.15 version.

The label must be an int or a float (always). If you have strings, you must convert them to ints indicating your different labels.

Pytorch and in general any deep learning framework cannot deal with string labels. So internally, string labels are always converted to ints, indicating the different labels.

**Comment by naty88** [comment]
Hi I have the last pytorch version (1.8.1+cu101), but have got the same RuntimeError: Found dtype Long but expected Float.
For fine-tuning I don't use any labels, only the list of sentences. 
If I test the code with the example from [here](https://www.sbert.net/docs/training/overview.html) I still get the same Error with
`model.fit(train_objectives=[(train_dataloader, train_loss)], epochs=1, warmup_steps=10)`
For fine-tune I use the model:
`model = SentenceTransformer('T-Systems-onsite/german-roberta-sentence-transformer-v2')`

**Comment by nreimers** [comment]
@naty88 
Appears your labels are ints. But you need to pass floats

**Comment by naty88** [comment]
Thank you for your answer. Actually, I don't have any labels, because I need only the embedding, so I have dropped it at all. But the error was because of the label. If I keep label and set it any float number, it works. 
But I'm wondering why it is not possible, not to write any label, use only the list of sentences?
Like... `train_examples = [InputExample(texts=sentence_list)]`

**Comment by nreimers** [comment]
Depending on the loss the label is needed or not. For cosine similarity loss, the label is mandatory. For other losses, like MultiplNegativeRankingLoss or TripletLoss, the label is not used

**Comment by naty88** [comment]
Thank you, I will try other losses then.

**Comment by lee9871** [comment]
train_loss = losses.CosineSimilarityLoss(model)
warmup_steps = math.ceil(len(train_dataloader) * num_epochs * 0.1) #10% of train data for warm-up
model.fit(train_objectives=[(train_dataloader, train_loss)],
          evaluator=evaluator,
          epochs=num_epochs,
          evaluation_steps=1000,
          warmup_steps=warmup_steps,
          output_path=model_save_path
          )
loss_value.backward() RuntimeError: Found dtype Long but expected Float
i need help~~ 
i try change train_losst= losses.SoftmaxLoss(model=model, sentence_embedding_dimension=model.get_sentence_embedding_dimension(), num_labels=train_num_labels)

have error :evaluator   TypeError: __call__() missing 1 required positional argument: 'loss'

**Comment by chintanckg** [comment]
You are doing supervised training without labels, this will not work. Please try un-supervised training (well documented on the sentence-transformers site).

Issue can be marked closed.
