### ISSUE TITLE
OSError: [Errno 24] Too many open files

### ISSUE THREAD

**Issue by ShoubhikBanerjee** [UKPLab/sentence-transformers#355]
When trying with large CSV (ex, 50K rows).

It gives : 

`OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/resource_sharer.py", line 149, in _serve
    send(conn, destination_pid)
  File "/usr/lib/python3.6/multiprocessing/resource_sharer.py", line 50, in send
    reduction.send_handle(conn, new_fd, pid)
  File "/usr/lib/python3.6/multiprocessing/reduction.py", line 176, in send_handle
    with socket.fromfd(conn.fileno(), socket.AF_UNIX, socket.SOCK_STREAM) as s:
  File "/usr/lib/python3.6/socket.py", line 460, in fromfd
    nfd = dup(fd)
`

on pressing ctr+c : 

`Traceback (most recent call last):
  File "Try.py", line 40, in <module>
    sentence_embeddings = model.encode(documents)
  File "/home/abc/.local/lib/python3.6/site-packages/sentence_transformers/SentenceTransformer.py", line 151, in encode
    sentences_tokenized = list(p.imap(self.tokenize, sentences, chunksize=self.parallel_tokenization_chunksize))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 611, in __exit__
    self.terminate()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 541, in terminate
    self._terminate()
  File "/usr/lib/python3.6/multiprocessing/util.py", line 186, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 589, in _terminate_pool
    p.terminate()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 116, in terminate
    self._popen.terminate()
AttributeError: 'NoneType' object has no attribute 'terminate'
Error in sys.excepthook:
`.

Could you please help me with this issue.  Thank You.  It works fine with small csv .

**Comment by nreimers** [comment]
It looks like there is an issue with the parallel tokenization, that forks several processes. To fix it, you can disable it:

```
model = SentenceTransformer(...)
model.parallel_tokenization = False
model.encode(...)
```

**Comment by ShoubhikBanerjee** [comment]
Yes ! It is working after that. Thanx
