### ISSUE TITLE
error 'can't convert CUDA tensor to numpy' in example

### ISSUE THREAD

**Issue by anish9208** [UKPLab/sentence-transformers#360]
File : examples/applications/semantic_search.py 
Env : CUDA/GPU enabled
command: `python semantic_search.py `

Error message : 

> Traceback (most recent call last):
  File "semantic_search.py", line 38, in <module>
    top_results = np.argpartition(-cos_scores, range(top_k))[0:top_k]
  File "<__array_function__ internals>", line 6, in argpartition
  File "/home/devops/anaconda3/envs/ad/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 830, in argpartition
    return _wrapfunc(a, 'argpartition', kth, axis=axis, kind=kind, order=order)
  File "/home/devops/anaconda3/envs/ad/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 58, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/home/devops/anaconda3/envs/ad/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 47, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
  File "/home/devops/anaconda3/envs/ad/lib/python3.7/site-packages/numpy/core/_asarray.py", line 85, in asarray
    return array(a, dtype, copy=False, order=order)
  File "/home/devops/anaconda3/envs/ad/lib/python3.7/site-packages/torch/tensor.py", line 486, in __array__
    return self.numpy()
TypeError: can't convert CUDA tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

Solution : 
adding  `cos_scores = cos_scores.cpu()` before line 38 will  do the job

**Comment by lefnire** [comment]
Looks like their latest code does `.cpu()` as needed https://github.com/UKPLab/sentence-transformers/blob/master/sentence_transformers/util.py#L77
