### ISSUE TITLE
Issues adding data to ES 

### ISSUE THREAD

**Issue by gavishpoddar** [UKPLab/sentence-transformers#387]
I was trying to use an example from `examples/applications/semantic_search_quora_elasticsearch.py` but was unable to i checked the ES.

```
(venv) gdev@GDevs-iMac sent_similarity % curl -XGET 'localhost:9200'
{
  "name" : "elasticsearch1",
  "cluster_name" : "docker-cluster",
  "cluster_uuid" : "fVUkJJH8T46ubNkQQi4wEA",
  "version" : {
    "number" : "7.8.0",
    "build_flavor" : "default",
    "build_type" : "docker",
    "build_hash" : "757314695644ea9a1dc2fecd26d1a43856725e65",
    "build_date" : "2020-06-14T19:35:50.234439Z",
    "build_snapshot" : false,
    "lucene_version" : "8.5.1",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}

```
it seems fine. but still, it is unable to add data to ES. With error

```
(venv) gdev@GDevs-iMac sent_similarity % python test.py
Index data (you can stop it by pressinc Ctrl+C once):
Batches: 100%|██████████████████████████████████████████████████████████████████████████████████████████| 16/16 [00:08<00:00,  2.00it/s]
WARNING:elasticsearch:POST http://localhost:9200/_bulk [status:400 request:0.629s]██████████████████████| 16/16 [00:08<00:00,  2.34it/s]
  0%|                                                                                                        | 0/100000 [00:09<?, ?it/s]
During index an exception occured. Continue


Please enter a question: ^Z
zsh: suspended  python test.py
```
 So I tried removing try and ended up with 

[]((venv) gdev@GDevs-iMac sent_similarity % python test.py
Index data (you can stop it by pressinc Ctrl+C once):
Batches: 100%|██████████████████████████████████████████████████████████████████████████████████████████| 16/16 [00:06<00:00,  2.58it/s]
WARNING:elasticsearch:POST http://localhost:9200/_bulk [status:400 request:0.773s]██████████████████████| 16/16 [00:06<00:00,  2.15it/s]
  0%|                                                                                                        | 0/100000 [00:07<?, ?it/s]
Traceback (most recent call last):
  File "test.py", line 89, in <module>
    helpers.bulk(es, bulk_data)
  File "/Users/gdev/PycharmProjects/sent_similarity/venv/lib/python3.7/site-packages/elasticsearch/helpers/actions.py", line 373, in bulk
    for ok, item in streaming_bulk(client, actions, *args, **kwargs):
  File "/Users/gdev/PycharmProjects/sent_similarity/venv/lib/python3.7/site-packages/elasticsearch/helpers/actions.py", line 303, in streaming_bulk
    **kwargs
  File "/Users/gdev/PycharmProjects/sent_similarity/venv/lib/python3.7/site-packages/elasticsearch/helpers/actions.py", line 230, in _process_bulk_chunk
    for item in gen:
  File "/Users/gdev/PycharmProjects/sent_similarity/venv/lib/python3.7/site-packages/elasticsearch/helpers/actions.py", line 179, in _process_bulk_chunk_error
    raise error
  File "/Users/gdev/PycharmProjects/sent_similarity/venv/lib/python3.7/site-packages/elasticsearch/helpers/actions.py", line 218, in _process_bulk_chunk
    resp = client.bulk("\n".join(bulk_actions) + "\n", *args, **kwargs)
  File "/Users/gdev/PycharmProjects/sent_similarity/venv/lib/python3.7/site-packages/elasticsearch/client/utils.py", line 152, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/Users/gdev/PycharmProjects/sent_similarity/venv/lib/python3.7/site-packages/elasticsearch/client/__init__.py", line 449, in bulk
    body=body,
  File "/Users/gdev/PycharmProjects/sent_similarity/venv/lib/python3.7/site-packages/elasticsearch/transport.py", line 392, in perform_request
    raise e
  File "/Users/gdev/PycharmProjects/sent_similarity/venv/lib/python3.7/site-packages/elasticsearch/transport.py", line 365, in perform_request
    timeout=timeout,
  File "/Users/gdev/PycharmProjects/sent_similarity/venv/lib/python3.7/site-packages/elasticsearch/connection/http_urllib3.py", line 269, in perform_request
    self._raise_error(response.status, raw_data)
  File "/Users/gdev/PycharmProjects/sent_similarity/venv/lib/python3.7/site-packages/elasticsearch/connection/base.py", line 301, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.RequestError: RequestError(400, 'action_request_validation_exception', 'Validation Failed: 1: index is missing;2: index is missing;3: index is missing;4: index is missing;5: index is missing;6: index is missing;7: index is missing;8: index is missing;9: index is missing;10: index is missing;11: index is missing;12: index is missing;13: index is missing;14: index is missing;15: index is missing;16: index is missing;17: index is missing;18: index is missing;19: index is missing;20: index is missing;21: index is missing;22: index is missing;23: index is missing;24: index is missing;25: index is missing;26: index is missing;27: index is missing;28: index is missing;29: index is missing;30: index is missing;31: index is missing;32: index is missing;33: index is missing;34: index is missing;35: index is missing;36: index is missing;37: index is missing;38: index is missing;39: index is missing;40: index is missing;41: index is missing;42: index is missing;43: index is missing;44: index is missing;45: ...........it goes on.)
 

Is there something wrong or my bad please help.
Thanks

**Comment by nreimers** [comment]
Hi @gavishpoddar 
Thanks for pointing this out.

I fixed the example, it should be working now.

Note, line 56 checks if the index already exists. If so, no new data will be indexed. You might uncomment that line or ensure that the created index is deleted, before starting the script.

**Comment by gavishpoddar** [comment]
Thanks so much, @nreimers your help was great and right in time. And the bug fix of line **83  is also now fixed **
