### ISSUE TITLE
AttributeError: 'BertTokenizer' object has no attribute 'prepare_for_model'

### ISSUE THREAD

**Issue by abhishekju06** [UKPLab/sentence-transformers#427]
Hi,

 print(torch.__version__)
1.6.0
I am experiencing this error for any pretrained model that I load.
AttributeError: 'BertTokenizer' object has no attribute 'prepare_for_model'
python
Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from sentence_transformers import SentenceTransformer
>>> model = SentenceTransformer('bert-base-nli-mean-tokens')
>>> sentences = ['This framework generates embeddings for each input sentence',
...     'Sentences are passed as a list of string.', 
...     'The quick brown fox jumps over the lazy dog.']
>>> sentence_embeddings = model.encode(sentences)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/abhishek/PhD/VQA/sentence-transformers-master/sentence_transformers/SentenceTransformer.py", line 171, in encode
    for features in iterator:
  File "/home/abhishek/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/home/abhishek/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 403, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/abhishek/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/abhishek/PhD/VQA/sentence-transformers-master/sentence_transformers/SentenceTransformer.py", line 414, in smart_batching_collate_text_only
    sentence_features = self.get_sentence_features(text, max_seq_len)
  File "/home/abhishek/PhD/VQA/sentence-transformers-master/sentence_transformers/SentenceTransformer.py", line 320, in get_sentence_features
    return self._first_module().get_sentence_features(*features)
  File "/home/abhishek/PhD/VQA/sentence-transformers-master/sentence_transformers/models/BERT.py", line 66, in get_sentence_features
    return self.tokenizer.prepare_for_model(tokens, max_length=pad_seq_length, padding='max_length', return_tensors='pt', truncation=True, prepend_batch_axis=True)
AttributeError: 'BertTokenizer' object has no attribute 'prepare_for_model'
>>>

**Comment by nreimers** [comment]
It appears that you have the wrong version of transformers installed.

**Comment by abhishekju06** [comment]
The problem occurred as I didn't create a separate environment for transformers and sentence-transformers.
