### ISSUE TITLE
cross-encoder with "CEBinaryClassificationEvaluator"

### ISSUE THREAD

**Issue by ReySadeghi** [UKPLab/sentence-transformers#666]
Hi, 
in term of using cross-encoder with "CEBinaryClassificationEvaluator", I got this error:

Traceback (most recent call last):
  File "crossEncoder.py", line 77, in <module>
    output_path=model_save_path2)
  File "/usr/local/lib/python3.6/dist-packages/sentence_transformers/cross_encoder/CrossEncoder.py", line 202, in fit
    self._eval_during_training(evaluator, output_path, save_best_model, epoch, training_steps, callback)
  File "/usr/local/lib/python3.6/dist-packages/sentence_transformers/cross_encoder/CrossEncoder.py", line 280, in _eval_during_training
    score = evaluator(self, output_path=output_path, epoch=epoch, steps=steps)
  File "/usr/local/lib/python3.6/dist-packages/sentence_transformers/cross_encoder/evaluation/CEBinaryClassificationEvaluator.py", line 50, in __call__
    acc, acc_threshold = BinaryClassificationEvaluator.find_best_acc_and_threshold(pred_scores, self.labels, True)
  File "/usr/local/lib/python3.6/dist-packages/sentence_transformers/evaluation/BinaryClassificationEvaluator.py", line 127, in find_best_acc_and_threshold
    rows = sorted(rows, key=lambda x: x[0], reverse=high_score_more_similar)
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by nreimers** [comment]
Hi @ReySadeghi 
This error happens when the data is passed in a wrong format. Make sure to check that everything is correct when you initialize the evaluator

**Comment by ReySadeghi** [comment]
I'm sure that my data is on the correct format, and I tried my data with "CESoftmaxAccuracyEvaluator" and it was ok but with "CEBinaryClassificationEvaluator" I got error.

**Comment by Yevgnen** [comment]
Same issue. You will need to pass `num_labels=1` when initializing the`CrossEncoder`, not `num_labels=2`.
