### ISSUE TITLE
RoBERTa fine-tuning pyo3_runtime.PanicException: no entry found for key

### ISSUE THREAD

**Issue by bhavikm** [UKPLab/sentence-transformers#675]
When fine-tuning 'roberta-large-nli-stsb-mean-tokens' with the following setup:

model.fit(
	train_objectives=[(train_dataloader, train_loss)],
        epochs=num_epochs, 
        warmup_steps=warmup_steps, 
        evaluator=evaluator, 
        evaluation_steps=1000,
        output_path=model_save_path)

I get the following error on attempted model save at evaluation:

Traceback (most recent call last):
  File "train_model.py", line 110, in <module>
    main()
  File "train_model.py", line 91, in main
    output_path=model_save_path)
  File "/floyd/home/venv/lib/python3.7/site-packages/sentence_transformers/SentenceTransformer.py", line 576, in fit
    training_steps, callback)
  File "/floyd/home/venv/lib/python3.7/site-packages/sentence_transformers/SentenceTransformer.py", line 605, in _eval_during_training
    self.save(output_path)
  File "/floyd/home/venv/lib/python3.7/site-packages/sentence_transformers/SentenceTransformer.py", line 361, in save
    module.save(model_path)
  File "/floyd/home/venv/lib/python3.7/site-packages/sentence_transformers/models/Transformer.py", line 90, in save
    self.tokenizer.save_pretrained(output_path)
  File "/floyd/home/venv/lib/python3.7/site-packages/transformers/tokenization_utils_base.py", line 2009, in save_pretrained
    filename_prefix=filename_prefix,
  File "/floyd/home/venv/lib/python3.7/site-packages/transformers/tokenization_utils_fast.py", line 528, in _save_pretrained
    vocab_files = self.save_vocabulary(save_directory, filename_prefix=filename_prefix)
  File "/floyd/home/venv/lib/python3.7/site-packages/transformers/models/gpt2/tokenization_gpt2_fast.py", line 172, in save_vocabulary
    files = self._tokenizer.model.save(save_directory, name=filename_prefix)
pyo3_runtime.PanicException: no entry found for key

Doesn't occur with with 'bert-base-nli-stsb-mean-tokens' or 'bert-large-nli-stsb-mean-tokens'

**Comment by nreimers** [comment]
Try 'nli-roberta-large' or stsb-roberta-large.

It is the same model as the roberta-large-nli... models, but the config-file for the tokenizer was updated to the most recent version of transformers.

**Comment by bhavikm** [comment]
Thanks this solved the issue

**Comment by paulowiz** [comment]
What need to input on 'roberta-large-nli-stsb-mean-tokens'  to works?

**Comment by nreimers** [comment]
@paulowiz look at what I wrote above
