### ISSUE TITLE
using run_squad.py for predict and specifying config_name as path, config.json not found

### ISSUE THREAD

**Issue by mfeblowitz** [UKPLab/sentence-transformers#81]
Using transformers code tagged as v2.2.0

The situation is that, when running a predict-only task and specifying 1) an explicit path for a fine-tuned albert model and 2) specifying a specific path to the corresponding config.json file, run_squad attempts to seek the config file in the location of the --output_dir.

It appears that, when specifying config_name as a full path, the specification is ignored and run_squad looks in the specified _output_dir_ location for config.json. Since I am automatically generating several output dirs during the course of running my pipeline, it is not convenient nor sensible for me to also copy the config file to each result directory.

To be concrete, I am trying to specify that the config file should come from the training output model directory:
```
--config_name /home/.../albert_models/squad2/config.json
```
and that the eval/predict output should go to a result directory:
```
--output_dir /home/.../pipeline_results/session_id_1234/output/workdirs/0.0.0
```
When I do this I see the following error:
```
12/12/2019 19:18:24 - INFO - __main__ -   Evaluate the following checkpoints: ['/home/.../pipeline_results/session_id_1234/output/workdirs/0.0.0'']                                                                                                                      Traceback (most recent call last):                                                                                                            File "/home/.../transformers/transformers/configuration_utils.py", line 134, in from_pretrained                                 resolved_config_file = cached_path(config_file, cache_dir=cache_dir, force_download=force_download, proxies=proxies)                      
File "/home/.../transformers/transformers/file_utils.py", line 182, in cached_path raise EnvironmentError("file {} not found".format(url_or_filename))
OSError: file /home//home/.../pipeline_results/session_id_1234/output/workdirs/0.0.0/config.json' not found                                                                                                                                                                    During handling of the above exception, another exception occurred: 
Traceback (most recent call last):                                                                                                          
  File "/home/.../transformers/transformers/configuration_utils.py", line 134, in from_pretrained                             
    resolved_config_file = cached_path(config_file, cache_dir=cache_dir, force_download=force_download, proxies=proxies)                    
  File "/home/.../transformers/transformers/file_utils.py", line 182, in cached_path                                          
    raise EnvironmentError("file {} not found".format(url_or_filename))                                                                     
OSError: file /home/.../pipeline_results/session_id_1234/output/workdirs/0.0.0'/config.json not found  
```

**Comment by nreimers** [comment]
Hi @mfeblowitz 
I think you got the wrong repository.

Looks like your question would be more appropriate here:
https://github.com/huggingface/transformers

Best
Nils Reimers

**Comment by mfeblowitz** [comment]
Ugh - my bad. Thanks!
