### ISSUE TITLE
OSError: Can't load config for 'cross-encoder/ms-marco-TinyBERT-L-6'

### ISSUE THREAD

**Issue by chenzhutian** [UKPLab/sentence-transformers#810]
python 3.6
pytorch 1.7.1
Is the model name changed?
Thanks!

```
Traceback (most recent call last):
  File "/home/zhutian/.conda/envs/infospace/lib/python3.6/site-packages/transformers/configuration_utils.py", line 353, in get_config_dict
    raise EnvironmentError
OSError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cross-wiki.py", line 18, in <module>
    cross_encoder = CrossEncoder('cross-encoder/ms-marco-TinyBERT-L-6')
  File "/home/zhutian/.conda/envs/infospace/lib/python3.6/site-packages/sentence_transformers/cross_encoder/CrossEncoder.py", line 36, in __init__
    self.config = AutoConfig.from_pretrained(model_name)
  File "/home/zhutian/.conda/envs/infospace/lib/python3.6/site-packages/transformers/configuration_auto.py", line 272, in from_pretrained
    config_dict, _ = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/zhutian/.conda/envs/infospace/lib/python3.6/site-packages/transformers/configuration_utils.py", line 362, in get_config_dict
    raise EnvironmentError(msg)
OSError: Can't load config for 'cross-encoder/ms-marco-TinyBERT-L-6'. Make sure that:

- 'cross-encoder/ms-marco-TinyBERT-L-6' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'cross-encoder/ms-marco-TinyBERT-L-6' is the correct path to a directory containing a config.json file
```

**Comment by nreimers** [comment]
The name is correct:
https://huggingface.co/cross-encoder/ms-marco-TinyBERT-L-6

Appears to be some issue with your environment

**Comment by chenzhutian** [comment]
any hints?
Thanks!

**Comment by nreimers** [comment]
From that truncated error message sadly not

**Comment by chenzhutian** [comment]
I try to use "nboost/pt-bert-large-msmarco" and it works. super wried.

**Comment by chenzhutian** [comment]
![image](https://user-images.githubusercontent.com/3315274/110910964-e7431200-82c6-11eb-8458-0860055b74a8.png)
I git clone the model and load it in the local machine, and it shows me this

**Comment by chenzhutian** [comment]
upgrade transformer from 3.1.0 to 4.3.3 fix this issue
