### ISSUE TITLE
AttributeError: module 'sentence_transformers.models' has no attribute 'CLIPModel

### ISSUE THREAD

**Issue by rajasekar-venkatesan** [UKPLab/sentence-transformers#838]
2021-03-27 06:36:33.776 Load SentenceTransformer from folder: /home/appuser/.cache/torch/sentence_transformers/sbert.net_models_clip-ViT-B-32

2021-03-27 06:36:33.777 Uncaught app exception

Traceback (most recent call last):

  File "/home/appuser/.local/lib/python3.7/site-packages/sentence_transformers/util.py", line 299, in import_from_string

    return getattr(module, class_name)

AttributeError: module 'sentence_transformers.models' has no attribute 'CLIPModel'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/home/appuser/.local/lib/python3.7/site-packages/streamlit/script_runner.py", line 333, in _run_script

    exec(code, module.__dict__)

  File "/app/image-search/host_streamlit.py", line 3, in <module>

    from image_search import *

  File "/app/image-search/image_search.py", line 17, in <module>

    model = SentenceTransformer('clip-ViT-B-32')

  File "/home/appuser/.local/lib/python3.7/site-packages/sentence_transformers/SentenceTransformer.py", line 120, in __init__

    module_class = import_from_string(module_config['type'])

  File "/home/appuser/.local/lib/python3.7/site-packages/sentence_transformers/util.py", line 302, in import_from_string

    raise ImportError(msg)

ImportError: Module "sentence_transformers.models" does not define a "CLIPModel" attribute/class

**Comment by nreimers** [comment]
You need Version 1.0.0 or newer of Sentence Transformers

**Comment by rajasekar-venkatesan** [comment]
I'm using version 1.0.3

**Comment by vgrabovets** [comment]
You need to install torchvision

**Comment by rajasekar-venkatesan** [comment]
> You need to install torchvision

That worked!! Thanks much
