### ISSUE TITLE
Model checkpoint load problem

### ISSUE THREAD

**Issue by pablogranolabar** [UKPLab/sentence-transformers#923]
So I am trying to Docker containerize sentence-transformers for CPU inference and I cannot figure this out. I have a Dockerfile which deploys perfectly using HuggingFace model checkpoints but for whatever reason I am getting filesystem permission errors as well as file not found for the downloaded models?

Here is the relevant Dockerfile:

FROM public.ecr.aws/lambda/python:3.8

# copy requirements.txt file to the container
COPY requirements.txt ./

# upgrade pip and install the python requirements from requirements.txt
RUN python3.8 -m pip install \
        --upgrade pip
RUN python3.8 -m pip install \
        -r requirements.txt

# Copy function code
COPY app.py ./

# Install the runtime interface client
RUN python3.8 -m pip install \
        awslambdaric

# clean up image for small container
RUN find . -type d -name "tests" -exec rm -rf {} +
RUN find . -type d -name "__pycache__" -exec rm -rf {} +
RUN find . -type d -name "include" -exec rm -rf {} +
RUN rm -rf ./{caffe2,wheel,wheel-*,pkg_resources,boto*,aws*,pip,pip-*,pipenv,setuptools}
RUN rm -rf ./{*.egg-info,*.dist-info}
RUN find . -name \*.pyc -delete
RUN find . -type d -name "test" -exec rm -rf {} +
RUN ls -R -al

# update linux libraries
RUN yum update -y

# install python3 and unzip
RUN yum install -y python3 unzip

# pull model files
RUN mkdir ./model
RUN curl https://somewhere.com/model.zip  -o ./model/model.zip
RUN unzip ./model/model.zip -d ./model
RUN chmod 644 ./model
RUN chmod -R 644 ./model/*
RUN rm ./model/model.zip

WORKDIR ./
ENTRYPOINT [ "python3", "-m", "awslambdaric" ]
CMD [ "app.lambda_handler" ]

****************

And the app.py:

from __future__ import print_function
import json, time
import urllib.request
from jose import jwk, jwt
from jose.utils import base64url_decode
from sentence_transformers import SentenceTransformer, util

model = ModelFunction('/model')

def lambda_handler(event, context):

    body = json.loads(event['body'])

    token = body['jwttoken']
    utterance = body['utterance']
    comparestring = body['comparestring']

    # generate embeddings for each phrase
    embeddings1 = model.encode(utterance, convert_to_tensor=True)
    embeddings2 = model.encode(comparestring, convert_to_tensor=True)

    # compute score
    score = util.embeddings(embeddings1, embeddings2)

    # output score
    print("Score:")
    print(score.item())

    return {
        "statusCode": 200,
        "score": json.dums(score.item())
    }

    # the following is useful to make this script executable in both
    # AWS Lambda and any other local environments
if __name__ == '__main__':
    event = {
        'token': '',
        'email': 'somewhere@somewhere.com'}
    lambda_handler(event, None)

****************

A couple of the relevant error messages:

[ERROR] PermissionError: [Errno 13] Permission denied: './model/modules.json'
Traceback (most recent call last):
  File "/var/lang/lib/python3.8/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/var/lang/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/task/app.py", line 8, in <module>
    model = model('./model')
  File "/var/lang/lib/python3.8/site-packages/model/model.py", line 115, in __init__
    with open(os.path.join(model_path, 'modules.json')) as fIn:

****************

and

[ERROR] FileNotFoundError: [Errno 2] No such file or directory: '/home/sbx_user1051/.cache/model'
Traceback (most recent call last):
  File "/var/lang/lib/python3.8/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/var/lang/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/task/app.py", line 8, in <module>
    model = model('/model')
  File "/var/lang/lib/python3.8/site-packages/model/model.py", line 101, in __init__
    shutil.rmtree(model_path)
  File "/var/lang/lib/python3.8/shutil.py", line 709, in rmtree
    onerror(os.lstat, path, sys.exc_info())
  File "/var/lang/lib/python3.8/shutil.py", line 707, in rmtree
    orig_st = os.lstat(path)

**Comment by nreimers** [comment]
Sadly not sure what causes this issue. Looks like the file system does not allow the access. Not sure what is the cause or how to fix it.

**Comment by dsivakumar** [comment]
I tried with aws Lambda + container arch, built a docker and tested locally, worked fine but on lambda function get this error
/home is read only and /tmp and /var/task are only read/write libaries.

I tried to set os.environ['SENTENCE_TRANSFORMERS_HOME'] = '/var/task' works on local docker but fails in aws lambda and container.

I assume cache_folder is the issue  
snapshot_download(model_name_or_path,                                     cache_dir=cache_folder,

[ERROR] OSError: [Errno 30] Read-only file system: '/home/sbx_user1051'
Traceback (most recent call last):
  File "/var/lang/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/var/task/app.py", line 10, in <module>
    model =  SBertSummarizer('paraphrase-MiniLM-L6-v2')
  File "/var/task/summarizer/sbert.py", line 26, in __init__
    model_func = SBertEmbedding(model)
  File "/var/task/summarizer/transformer_embeddings/sbert_embedding.py", line 17, in __init__
    self.sbert_model = SentenceTransformer(model)
  File "/var/task/sentence_transformers/SentenceTransformer.py", line 86, in __init__
    snapshot_download(model_name_or_path,
  File "/var/task/sentence_transformers/util.py", line 456, in snapshot_download
    os.makedirs(nested_dirname, exist_ok=True)
  File "/var/lang/lib/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/var/lang/lib/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/var/lang/lib/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  [Previous line repeated 1 more time]
  File "/var/lang/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)

**Comment by dsivakumar** [comment]
this is the one I tried https://github.com/dmmiller612/bert-extractive-summarizer for summary of text.

**Comment by dsivakumar** [comment]
Resolved by setting in aws Lambda configuration->Environment variables  HOME to /tmp !! All works fine!!!
