### ISSUE TITLE
Would you like to release the detail about how to train the clip-ViT-B-32-multilingual-v1?

### ISSUE THREAD

**Issue by RyanHuangNLP** [UKPLab/sentence-transformers#980]
How to train the clip-ViT-B-32-multilingual-v1

**Comment by nreimers** [comment]
You can find the code and explanation here
https://sbert.net/examples/training/multilingual/README.html

As teacher we use the clip model and as student the xlm-Roberta-base model.

**Comment by RyanHuangNLP** [comment]
@nreimers Thanks for response.

**Comment by yafengchen** [comment]
Hi, were you able to train the multilingual model? I set the teacher model to CLIP. Also, for the student model, I changed 
```
pooling_model = models.Pooling(word_embedding_model.get_word_embedding_dimension())
```
to
```
pooling_model = models.Pooling(512)
```
when running the fit step, it still gives me the error "The size of tensor a (768) must match the size of tensor b (512) at non-singleton dimension 1". How to change the output of the student model to 512?

**Comment by nreimers** [comment]
You have to add a dense layer on top of the pooling layer that transformers the 768 to 512 dimensions

**Comment by yj4165** [comment]
Hi, what is the train data used in the clip-ViT-B-32-multilingual-v1?

**Comment by nreimers** [comment]
@yj4165 https://huggingface.co/datasets/sentence-transformers/parallel-sentences

**Comment by yj4165** [comment]
@nreimers Thanks for response.

**Comment by Lauler** [comment]
@nreimers To load a CLIP model for multilingual training, is the correct way to use `SentenceTransformers()`? I get errors when trying to load CLIPModels from Huggingface with `SentenceTransformer`. 

```python
from sentence_transformers import SentenceTransformer
teacher_model_name = "openai/clip-vit-base-patch32" 
teacher_model = SentenceTransformer(teacher_model_name)
```
```
No sentence-transformers model found with name /ceph/hpc/home/eufatonr/.cache/torch/sentence_transformers/openai_clip-vit-base-patch32. Creating a new one with MEAN pooling.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/ceph/hpc/home/eufatonr/.conda/envs/sbert/lib/python3.9/site-packages/sentence_transformers/SentenceTransformer.py", line 97, in __init__
    modules = self._load_auto_model(model_path)
  File "/ceph/hpc/home/eufatonr/.conda/envs/sbert/lib/python3.9/site-packages/sentence_transformers/SentenceTransformer.py", line 807, in _load_auto_model
    pooling_model = Pooling(transformer_model.get_word_embedding_dimension(), 'mean')
  File "/ceph/hpc/home/eufatonr/.conda/envs/sbert/lib/python3.9/site-packages/sentence_transformers/models/Transformer.py", line 82, in get_word_embedding_dimension
    return self.auto_model.config.hidden_size
  File "/ceph/hpc/home/eufatonr/.conda/envs/sbert/lib/python3.9/site-packages/transformers/configuration_utils.py", line 254, in __getattribute__
    return super().__getattribute__(key)
AttributeError: 'CLIPConfig' object has no attribute 'hidden_size'
```

If I try to load directly using CLIPModel class from `sentence_transformers.models`, that doesn't work either as the dataset loading expects the attribute/method `.encode()` to exist. I assume therefore it should be possible to load these models via `SentenceTransformer()`. 

Package versions:

transformers              4.25.1
sentence-transformers     2.2.2
