### ISSUE TITLE
Error loading paraphrase-multilingual-mpnet-base-v2 model

### ISSUE THREAD

**Issue by gongshaojie12** [UKPLab/sentence-transformers#988]
When I use sentence-transformers to load `paraphrase-multilingual-mpnet-base-v2`, the following error occurs:

```
100%|██████████| 1.02G/1.02G [01:53<00:00, 8.93MB/s]
Traceback (most recent call last):
  File "D:/NLU/test/tests/test_sentence_transformers.py", line 12, in <module>
    model = SentenceTransformer(model_name)
  File "D:\software\anaconda\envs\test\lib\site-packages\sentence_transformers\SentenceTransformer.py", line 121, in __init__
    module = module_class.load(os.path.join(model_path, module_config['path']))
  File "D:\software\anaconda\envs\test\lib\site-packages\sentence_transformers\models\Transformer.py", line 111, in load
    return Transformer(model_name_or_path=input_path, **config)
  File "D:\software\anaconda\envs\test\lib\site-packages\sentence_transformers\models\Transformer.py", line 29, in __init__
    self.tokenizer = AutoTokenizer.from_pretrained(model_name_or_path, cache_dir=cache_dir, **tokenizer_args)
  File "D:\software\anaconda\envs\test\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 395, in from_pretrained
    return tokenizer_class_fast.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "D:\software\anaconda\envs\test\lib\site-packages\transformers\tokenization_utils_base.py", line 1789, in from_pretrained
    resolved_vocab_files, pretrained_model_name_or_path, init_configuration, *init_inputs, **kwargs
  File "D:\software\anaconda\envs\test\lib\site-packages\transformers\tokenization_utils_base.py", line 1860, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "D:\software\anaconda\envs\test\lib\site-packages\transformers\models\xlm_roberta\tokenization_xlm_roberta_fast.py", line 144, in __init__
    **kwargs,
  File "D:\software\anaconda\envs\test\lib\site-packages\transformers\tokenization_utils_fast.py", line 93, in __init__
    fast_tokenizer = TokenizerFast.from_file(fast_tokenizer_file)
Exception: data did not match any variant of untagged enum PyPreTokenizerTypeWrapper at line 1 column 317718
```

My code is as follows:

```
from sentence_transformers import SentenceTransformer
model_name = "paraphrase-multilingual-mpnet-base-v2"
model = SentenceTransformer(model_name)
```

I use Windows 10. Please help me! Thank you very much!

**Comment by nreimers** [comment]
Update to the latest version of transformers and of tokenizers

**Comment by gongshaojie12** [comment]
OK. Thanks a lot. It works for me.

**Comment by alexwilson1** [comment]
This issue occurred for me even when specifying   `- transformers=4.6.1 `as a Conda dependency in my environment.yml (tokenizers was being installed as 0.10.1 by default when not specified, probably because the Tokenizers [Conda package](https://anaconda.org/conda-forge/tokenizers) has not been updated).

Specifying `- tokenizers==0.10.3` as a pip dependency in my environment.yml worked... thanks for the heads up!
